// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: construct/v1/common.proto

package client

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// SortFiel specifies which field to use for sorting results in list operations.
type SortFiel int32

const (
	// SORT_FIELD_UNSPECIFIED indicates no specific sort field is selected.
	SortFiel_SORT_FIELD_UNSPECIFIEDs SortFiel = 0
)

// Enum value maps for SortFiel.
var (
	SortFiel_name = map[int32]string{
		0: "SORT_FIELD_UNSPECIFIEDs",
	}
	SortFiel_value = map[string]int32{
		"SORT_FIELD_UNSPECIFIEDs": 0,
	}
)

func (x SortFiel) Enum() *SortFiel {
	p := new(SortFiel)
	*p = x
	return p
}

func (x SortFiel) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SortFiel) Descriptor() protoreflect.EnumDescriptor {
	return file_construct_v1_common_proto_enumTypes[0].Descriptor()
}

func (SortFiel) Type() protoreflect.EnumType {
	return &file_construct_v1_common_proto_enumTypes[0]
}

func (x SortFiel) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *SortFiel) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = SortFiel(num)
	return nil
}

// Deprecated: Use SortFiel.Descriptor instead.
func (SortFiel) EnumDescriptor() ([]byte, []int) {
	return file_construct_v1_common_proto_rawDescGZIP(), []int{0}
}

// SortOrde specifies the direction for sorting results in list operations.
type SortOrde int32

const (
	// SORT_ORDER_UNSPECIFIED indicates no specific sort order is selected.
	SortOrde_SORT_ORDER_UNSPECIFIEDs SortOrde = 0
)

// Enum value maps for SortOrde.
var (
	SortOrde_name = map[int32]string{
		0: "SORT_ORDER_UNSPECIFIEDs",
	}
	SortOrde_value = map[string]int32{
		"SORT_ORDER_UNSPECIFIEDs": 0,
	}
)

func (x SortOrde) Enum() *SortOrde {
	p := new(SortOrde)
	*p = x
	return p
}

func (x SortOrde) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SortOrde) Descriptor() protoreflect.EnumDescriptor {
	return file_construct_v1_common_proto_enumTypes[1].Descriptor()
}

func (SortOrde) Type() protoreflect.EnumType {
	return &file_construct_v1_common_proto_enumTypes[1]
}

func (x SortOrde) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *SortOrde) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = SortOrde(num)
	return nil
}

// Deprecated: Use SortOrde.Descriptor instead.
func (SortOrde) EnumDescriptor() ([]byte, []int) {
	return file_construct_v1_common_proto_rawDescGZIP(), []int{1}
}

var File_construct_v1_common_proto protoreflect.FileDescriptor

const file_construct_v1_common_proto_rawDesc = "" +
	"\n" +
	"\x19construct/v1/common.proto\x12\fconstruct.v1*'\n" +
	"\bSortFiel\x12\x1b\n" +
	"\x17SORT_FIELD_UNSPECIFIEDs\x10\x00*'\n" +
	"\bSortOrde\x12\x1b\n" +
	"\x17SORT_ORDER_UNSPECIFIEDs\x10\x00B,Z*github.com/furisto/construct/api/go/client"

var (
	file_construct_v1_common_proto_rawDescOnce sync.Once
	file_construct_v1_common_proto_rawDescData []byte
)

func file_construct_v1_common_proto_rawDescGZIP() []byte {
	file_construct_v1_common_proto_rawDescOnce.Do(func() {
		file_construct_v1_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_construct_v1_common_proto_rawDesc), len(file_construct_v1_common_proto_rawDesc)))
	})
	return file_construct_v1_common_proto_rawDescData
}

var file_construct_v1_common_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_construct_v1_common_proto_goTypes = []any{
	(SortFiel)(0), // 0: construct.v1.SortFiel
	(SortOrde)(0), // 1: construct.v1.SortOrde
}
var file_construct_v1_common_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_construct_v1_common_proto_init() }
func file_construct_v1_common_proto_init() {
	if File_construct_v1_common_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_construct_v1_common_proto_rawDesc), len(file_construct_v1_common_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_construct_v1_common_proto_goTypes,
		DependencyIndexes: file_construct_v1_common_proto_depIdxs,
		EnumInfos:         file_construct_v1_common_proto_enumTypes,
	}.Build()
	File_construct_v1_common_proto = out.File
	file_construct_v1_common_proto_goTypes = nil
	file_construct_v1_common_proto_depIdxs = nil
}
