// Code generated by MockGen. DO NOT EDIT.
// Source: ../v1/v1connect/agent.connect.go
//
// Generated by this command:
//
//	mockgen -source=../v1/v1connect/agent.connect.go -destination=./test/agent.connect_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	connect "connectrpc.com/connect"
	v1 "github.com/furisto/construct/api/go/v1"
	gomock "go.uber.org/mock/gomock"
)

// MockAgentServiceClient is a mock of AgentServiceClient interface.
type MockAgentServiceClient struct {
	ctrl     *gomock.Controller
	recorder *MockAgentServiceClientMockRecorder
	isgomock struct{}
}

// MockAgentServiceClientMockRecorder is the mock recorder for MockAgentServiceClient.
type MockAgentServiceClientMockRecorder struct {
	mock *MockAgentServiceClient
}

// NewMockAgentServiceClient creates a new mock instance.
func NewMockAgentServiceClient(ctrl *gomock.Controller) *MockAgentServiceClient {
	mock := &MockAgentServiceClient{ctrl: ctrl}
	mock.recorder = &MockAgentServiceClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAgentServiceClient) EXPECT() *MockAgentServiceClientMockRecorder {
	return m.recorder
}

// CreateAgent mocks base method.
func (m *MockAgentServiceClient) CreateAgent(arg0 context.Context, arg1 *connect.Request[v1.CreateAgentRequest]) (*connect.Response[v1.CreateAgentResponse], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAgent", arg0, arg1)
	ret0, _ := ret[0].(*connect.Response[v1.CreateAgentResponse])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateAgent indicates an expected call of CreateAgent.
func (mr *MockAgentServiceClientMockRecorder) CreateAgent(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAgent", reflect.TypeOf((*MockAgentServiceClient)(nil).CreateAgent), arg0, arg1)
}

// DeleteAgent mocks base method.
func (m *MockAgentServiceClient) DeleteAgent(arg0 context.Context, arg1 *connect.Request[v1.DeleteAgentRequest]) (*connect.Response[v1.DeleteAgentResponse], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteAgent", arg0, arg1)
	ret0, _ := ret[0].(*connect.Response[v1.DeleteAgentResponse])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteAgent indicates an expected call of DeleteAgent.
func (mr *MockAgentServiceClientMockRecorder) DeleteAgent(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAgent", reflect.TypeOf((*MockAgentServiceClient)(nil).DeleteAgent), arg0, arg1)
}

// GetAgent mocks base method.
func (m *MockAgentServiceClient) GetAgent(arg0 context.Context, arg1 *connect.Request[v1.GetAgentRequest]) (*connect.Response[v1.GetAgentResponse], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAgent", arg0, arg1)
	ret0, _ := ret[0].(*connect.Response[v1.GetAgentResponse])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAgent indicates an expected call of GetAgent.
func (mr *MockAgentServiceClientMockRecorder) GetAgent(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAgent", reflect.TypeOf((*MockAgentServiceClient)(nil).GetAgent), arg0, arg1)
}

// ListAgents mocks base method.
func (m *MockAgentServiceClient) ListAgents(arg0 context.Context, arg1 *connect.Request[v1.ListAgentsRequest]) (*connect.Response[v1.ListAgentsResponse], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAgents", arg0, arg1)
	ret0, _ := ret[0].(*connect.Response[v1.ListAgentsResponse])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListAgents indicates an expected call of ListAgents.
func (mr *MockAgentServiceClientMockRecorder) ListAgents(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAgents", reflect.TypeOf((*MockAgentServiceClient)(nil).ListAgents), arg0, arg1)
}

// UpdateAgent mocks base method.
func (m *MockAgentServiceClient) UpdateAgent(arg0 context.Context, arg1 *connect.Request[v1.UpdateAgentRequest]) (*connect.Response[v1.UpdateAgentResponse], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateAgent", arg0, arg1)
	ret0, _ := ret[0].(*connect.Response[v1.UpdateAgentResponse])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateAgent indicates an expected call of UpdateAgent.
func (mr *MockAgentServiceClientMockRecorder) UpdateAgent(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateAgent", reflect.TypeOf((*MockAgentServiceClient)(nil).UpdateAgent), arg0, arg1)
}

// MockAgentServiceHandler is a mock of AgentServiceHandler interface.
type MockAgentServiceHandler struct {
	ctrl     *gomock.Controller
	recorder *MockAgentServiceHandlerMockRecorder
	isgomock struct{}
}

// MockAgentServiceHandlerMockRecorder is the mock recorder for MockAgentServiceHandler.
type MockAgentServiceHandlerMockRecorder struct {
	mock *MockAgentServiceHandler
}

// NewMockAgentServiceHandler creates a new mock instance.
func NewMockAgentServiceHandler(ctrl *gomock.Controller) *MockAgentServiceHandler {
	mock := &MockAgentServiceHandler{ctrl: ctrl}
	mock.recorder = &MockAgentServiceHandlerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAgentServiceHandler) EXPECT() *MockAgentServiceHandlerMockRecorder {
	return m.recorder
}

// CreateAgent mocks base method.
func (m *MockAgentServiceHandler) CreateAgent(arg0 context.Context, arg1 *connect.Request[v1.CreateAgentRequest]) (*connect.Response[v1.CreateAgentResponse], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAgent", arg0, arg1)
	ret0, _ := ret[0].(*connect.Response[v1.CreateAgentResponse])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateAgent indicates an expected call of CreateAgent.
func (mr *MockAgentServiceHandlerMockRecorder) CreateAgent(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAgent", reflect.TypeOf((*MockAgentServiceHandler)(nil).CreateAgent), arg0, arg1)
}

// DeleteAgent mocks base method.
func (m *MockAgentServiceHandler) DeleteAgent(arg0 context.Context, arg1 *connect.Request[v1.DeleteAgentRequest]) (*connect.Response[v1.DeleteAgentResponse], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteAgent", arg0, arg1)
	ret0, _ := ret[0].(*connect.Response[v1.DeleteAgentResponse])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteAgent indicates an expected call of DeleteAgent.
func (mr *MockAgentServiceHandlerMockRecorder) DeleteAgent(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAgent", reflect.TypeOf((*MockAgentServiceHandler)(nil).DeleteAgent), arg0, arg1)
}

// GetAgent mocks base method.
func (m *MockAgentServiceHandler) GetAgent(arg0 context.Context, arg1 *connect.Request[v1.GetAgentRequest]) (*connect.Response[v1.GetAgentResponse], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAgent", arg0, arg1)
	ret0, _ := ret[0].(*connect.Response[v1.GetAgentResponse])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAgent indicates an expected call of GetAgent.
func (mr *MockAgentServiceHandlerMockRecorder) GetAgent(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAgent", reflect.TypeOf((*MockAgentServiceHandler)(nil).GetAgent), arg0, arg1)
}

// ListAgents mocks base method.
func (m *MockAgentServiceHandler) ListAgents(arg0 context.Context, arg1 *connect.Request[v1.ListAgentsRequest]) (*connect.Response[v1.ListAgentsResponse], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAgents", arg0, arg1)
	ret0, _ := ret[0].(*connect.Response[v1.ListAgentsResponse])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListAgents indicates an expected call of ListAgents.
func (mr *MockAgentServiceHandlerMockRecorder) ListAgents(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAgents", reflect.TypeOf((*MockAgentServiceHandler)(nil).ListAgents), arg0, arg1)
}

// UpdateAgent mocks base method.
func (m *MockAgentServiceHandler) UpdateAgent(arg0 context.Context, arg1 *connect.Request[v1.UpdateAgentRequest]) (*connect.Response[v1.UpdateAgentResponse], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateAgent", arg0, arg1)
	ret0, _ := ret[0].(*connect.Response[v1.UpdateAgentResponse])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateAgent indicates an expected call of UpdateAgent.
func (mr *MockAgentServiceHandlerMockRecorder) UpdateAgent(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateAgent", reflect.TypeOf((*MockAgentServiceHandler)(nil).UpdateAgent), arg0, arg1)
}
