// Code generated by MockGen. DO NOT EDIT.
// Source: ../v1/v1connect/message.connect.go
//
// Generated by this command:
//
//	mockgen -source=../v1/v1connect/message.connect.go -destination=./test/message.connect_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	connect "connectrpc.com/connect"
	v1 "github.com/furisto/construct/api/go/v1"
	gomock "go.uber.org/mock/gomock"
)

// MockMessageServiceClient is a mock of MessageServiceClient interface.
type MockMessageServiceClient struct {
	ctrl     *gomock.Controller
	recorder *MockMessageServiceClientMockRecorder
	isgomock struct{}
}

// MockMessageServiceClientMockRecorder is the mock recorder for MockMessageServiceClient.
type MockMessageServiceClientMockRecorder struct {
	mock *MockMessageServiceClient
}

// NewMockMessageServiceClient creates a new mock instance.
func NewMockMessageServiceClient(ctrl *gomock.Controller) *MockMessageServiceClient {
	mock := &MockMessageServiceClient{ctrl: ctrl}
	mock.recorder = &MockMessageServiceClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMessageServiceClient) EXPECT() *MockMessageServiceClientMockRecorder {
	return m.recorder
}

// CreateMessage mocks base method.
func (m *MockMessageServiceClient) CreateMessage(arg0 context.Context, arg1 *connect.Request[v1.CreateMessageRequest]) (*connect.Response[v1.CreateMessageResponse], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateMessage", arg0, arg1)
	ret0, _ := ret[0].(*connect.Response[v1.CreateMessageResponse])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateMessage indicates an expected call of CreateMessage.
func (mr *MockMessageServiceClientMockRecorder) CreateMessage(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateMessage", reflect.TypeOf((*MockMessageServiceClient)(nil).CreateMessage), arg0, arg1)
}

// DeleteMessage mocks base method.
func (m *MockMessageServiceClient) DeleteMessage(arg0 context.Context, arg1 *connect.Request[v1.DeleteMessageRequest]) (*connect.Response[v1.DeleteMessageResponse], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteMessage", arg0, arg1)
	ret0, _ := ret[0].(*connect.Response[v1.DeleteMessageResponse])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteMessage indicates an expected call of DeleteMessage.
func (mr *MockMessageServiceClientMockRecorder) DeleteMessage(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteMessage", reflect.TypeOf((*MockMessageServiceClient)(nil).DeleteMessage), arg0, arg1)
}

// GetMessage mocks base method.
func (m *MockMessageServiceClient) GetMessage(arg0 context.Context, arg1 *connect.Request[v1.GetMessageRequest]) (*connect.Response[v1.GetMessageResponse], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMessage", arg0, arg1)
	ret0, _ := ret[0].(*connect.Response[v1.GetMessageResponse])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMessage indicates an expected call of GetMessage.
func (mr *MockMessageServiceClientMockRecorder) GetMessage(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMessage", reflect.TypeOf((*MockMessageServiceClient)(nil).GetMessage), arg0, arg1)
}

// ListMessages mocks base method.
func (m *MockMessageServiceClient) ListMessages(arg0 context.Context, arg1 *connect.Request[v1.ListMessagesRequest]) (*connect.Response[v1.ListMessagesResponse], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListMessages", arg0, arg1)
	ret0, _ := ret[0].(*connect.Response[v1.ListMessagesResponse])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListMessages indicates an expected call of ListMessages.
func (mr *MockMessageServiceClientMockRecorder) ListMessages(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListMessages", reflect.TypeOf((*MockMessageServiceClient)(nil).ListMessages), arg0, arg1)
}

// Subscribe mocks base method.
func (m *MockMessageServiceClient) Subscribe(arg0 context.Context, arg1 *connect.Request[v1.SubscribeRequest]) (*connect.ServerStreamForClient[v1.SubscribeResponse], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Subscribe", arg0, arg1)
	ret0, _ := ret[0].(*connect.ServerStreamForClient[v1.SubscribeResponse])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Subscribe indicates an expected call of Subscribe.
func (mr *MockMessageServiceClientMockRecorder) Subscribe(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Subscribe", reflect.TypeOf((*MockMessageServiceClient)(nil).Subscribe), arg0, arg1)
}

// UpdateMessage mocks base method.
func (m *MockMessageServiceClient) UpdateMessage(arg0 context.Context, arg1 *connect.Request[v1.UpdateMessageRequest]) (*connect.Response[v1.UpdateMessageResponse], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateMessage", arg0, arg1)
	ret0, _ := ret[0].(*connect.Response[v1.UpdateMessageResponse])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateMessage indicates an expected call of UpdateMessage.
func (mr *MockMessageServiceClientMockRecorder) UpdateMessage(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateMessage", reflect.TypeOf((*MockMessageServiceClient)(nil).UpdateMessage), arg0, arg1)
}

// MockMessageServiceHandler is a mock of MessageServiceHandler interface.
type MockMessageServiceHandler struct {
	ctrl     *gomock.Controller
	recorder *MockMessageServiceHandlerMockRecorder
	isgomock struct{}
}

// MockMessageServiceHandlerMockRecorder is the mock recorder for MockMessageServiceHandler.
type MockMessageServiceHandlerMockRecorder struct {
	mock *MockMessageServiceHandler
}

// NewMockMessageServiceHandler creates a new mock instance.
func NewMockMessageServiceHandler(ctrl *gomock.Controller) *MockMessageServiceHandler {
	mock := &MockMessageServiceHandler{ctrl: ctrl}
	mock.recorder = &MockMessageServiceHandlerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMessageServiceHandler) EXPECT() *MockMessageServiceHandlerMockRecorder {
	return m.recorder
}

// CreateMessage mocks base method.
func (m *MockMessageServiceHandler) CreateMessage(arg0 context.Context, arg1 *connect.Request[v1.CreateMessageRequest]) (*connect.Response[v1.CreateMessageResponse], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateMessage", arg0, arg1)
	ret0, _ := ret[0].(*connect.Response[v1.CreateMessageResponse])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateMessage indicates an expected call of CreateMessage.
func (mr *MockMessageServiceHandlerMockRecorder) CreateMessage(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateMessage", reflect.TypeOf((*MockMessageServiceHandler)(nil).CreateMessage), arg0, arg1)
}

// DeleteMessage mocks base method.
func (m *MockMessageServiceHandler) DeleteMessage(arg0 context.Context, arg1 *connect.Request[v1.DeleteMessageRequest]) (*connect.Response[v1.DeleteMessageResponse], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteMessage", arg0, arg1)
	ret0, _ := ret[0].(*connect.Response[v1.DeleteMessageResponse])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteMessage indicates an expected call of DeleteMessage.
func (mr *MockMessageServiceHandlerMockRecorder) DeleteMessage(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteMessage", reflect.TypeOf((*MockMessageServiceHandler)(nil).DeleteMessage), arg0, arg1)
}

// GetMessage mocks base method.
func (m *MockMessageServiceHandler) GetMessage(arg0 context.Context, arg1 *connect.Request[v1.GetMessageRequest]) (*connect.Response[v1.GetMessageResponse], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMessage", arg0, arg1)
	ret0, _ := ret[0].(*connect.Response[v1.GetMessageResponse])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMessage indicates an expected call of GetMessage.
func (mr *MockMessageServiceHandlerMockRecorder) GetMessage(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMessage", reflect.TypeOf((*MockMessageServiceHandler)(nil).GetMessage), arg0, arg1)
}

// ListMessages mocks base method.
func (m *MockMessageServiceHandler) ListMessages(arg0 context.Context, arg1 *connect.Request[v1.ListMessagesRequest]) (*connect.Response[v1.ListMessagesResponse], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListMessages", arg0, arg1)
	ret0, _ := ret[0].(*connect.Response[v1.ListMessagesResponse])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListMessages indicates an expected call of ListMessages.
func (mr *MockMessageServiceHandlerMockRecorder) ListMessages(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListMessages", reflect.TypeOf((*MockMessageServiceHandler)(nil).ListMessages), arg0, arg1)
}

// Subscribe mocks base method.
func (m *MockMessageServiceHandler) Subscribe(arg0 context.Context, arg1 *connect.Request[v1.SubscribeRequest], arg2 *connect.ServerStream[v1.SubscribeResponse]) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Subscribe", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// Subscribe indicates an expected call of Subscribe.
func (mr *MockMessageServiceHandlerMockRecorder) Subscribe(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Subscribe", reflect.TypeOf((*MockMessageServiceHandler)(nil).Subscribe), arg0, arg1, arg2)
}

// UpdateMessage mocks base method.
func (m *MockMessageServiceHandler) UpdateMessage(arg0 context.Context, arg1 *connect.Request[v1.UpdateMessageRequest]) (*connect.Response[v1.UpdateMessageResponse], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateMessage", arg0, arg1)
	ret0, _ := ret[0].(*connect.Response[v1.UpdateMessageResponse])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateMessage indicates an expected call of UpdateMessage.
func (mr *MockMessageServiceHandlerMockRecorder) UpdateMessage(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateMessage", reflect.TypeOf((*MockMessageServiceHandler)(nil).UpdateMessage), arg0, arg1)
}
