// Code generated by MockGen. DO NOT EDIT.
// Source: ../v1/v1connect/modelprovider.connect.go
//
// Generated by this command:
//
//	mockgen -source=../v1/v1connect/modelprovider.connect.go -destination=./test/modelprovider.connect_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	connect "connectrpc.com/connect"
	v1 "github.com/furisto/construct/api/go/v1"
	gomock "go.uber.org/mock/gomock"
)

// MockModelProviderServiceClient is a mock of ModelProviderServiceClient interface.
type MockModelProviderServiceClient struct {
	ctrl     *gomock.Controller
	recorder *MockModelProviderServiceClientMockRecorder
	isgomock struct{}
}

// MockModelProviderServiceClientMockRecorder is the mock recorder for MockModelProviderServiceClient.
type MockModelProviderServiceClientMockRecorder struct {
	mock *MockModelProviderServiceClient
}

// NewMockModelProviderServiceClient creates a new mock instance.
func NewMockModelProviderServiceClient(ctrl *gomock.Controller) *MockModelProviderServiceClient {
	mock := &MockModelProviderServiceClient{ctrl: ctrl}
	mock.recorder = &MockModelProviderServiceClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockModelProviderServiceClient) EXPECT() *MockModelProviderServiceClientMockRecorder {
	return m.recorder
}

// CreateModelProvider mocks base method.
func (m *MockModelProviderServiceClient) CreateModelProvider(arg0 context.Context, arg1 *connect.Request[v1.CreateModelProviderRequest]) (*connect.Response[v1.CreateModelProviderResponse], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateModelProvider", arg0, arg1)
	ret0, _ := ret[0].(*connect.Response[v1.CreateModelProviderResponse])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateModelProvider indicates an expected call of CreateModelProvider.
func (mr *MockModelProviderServiceClientMockRecorder) CreateModelProvider(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateModelProvider", reflect.TypeOf((*MockModelProviderServiceClient)(nil).CreateModelProvider), arg0, arg1)
}

// DeleteModelProvider mocks base method.
func (m *MockModelProviderServiceClient) DeleteModelProvider(arg0 context.Context, arg1 *connect.Request[v1.DeleteModelProviderRequest]) (*connect.Response[v1.DeleteModelProviderResponse], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteModelProvider", arg0, arg1)
	ret0, _ := ret[0].(*connect.Response[v1.DeleteModelProviderResponse])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteModelProvider indicates an expected call of DeleteModelProvider.
func (mr *MockModelProviderServiceClientMockRecorder) DeleteModelProvider(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteModelProvider", reflect.TypeOf((*MockModelProviderServiceClient)(nil).DeleteModelProvider), arg0, arg1)
}

// GetModelProvider mocks base method.
func (m *MockModelProviderServiceClient) GetModelProvider(arg0 context.Context, arg1 *connect.Request[v1.GetModelProviderRequest]) (*connect.Response[v1.GetModelProviderResponse], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetModelProvider", arg0, arg1)
	ret0, _ := ret[0].(*connect.Response[v1.GetModelProviderResponse])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetModelProvider indicates an expected call of GetModelProvider.
func (mr *MockModelProviderServiceClientMockRecorder) GetModelProvider(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetModelProvider", reflect.TypeOf((*MockModelProviderServiceClient)(nil).GetModelProvider), arg0, arg1)
}

// ListModelProviders mocks base method.
func (m *MockModelProviderServiceClient) ListModelProviders(arg0 context.Context, arg1 *connect.Request[v1.ListModelProvidersRequest]) (*connect.Response[v1.ListModelProvidersResponse], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListModelProviders", arg0, arg1)
	ret0, _ := ret[0].(*connect.Response[v1.ListModelProvidersResponse])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListModelProviders indicates an expected call of ListModelProviders.
func (mr *MockModelProviderServiceClientMockRecorder) ListModelProviders(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListModelProviders", reflect.TypeOf((*MockModelProviderServiceClient)(nil).ListModelProviders), arg0, arg1)
}

// UpdateModelProvider mocks base method.
func (m *MockModelProviderServiceClient) UpdateModelProvider(arg0 context.Context, arg1 *connect.Request[v1.UpdateModelProviderRequest]) (*connect.Response[v1.UpdateModelProviderResponse], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateModelProvider", arg0, arg1)
	ret0, _ := ret[0].(*connect.Response[v1.UpdateModelProviderResponse])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateModelProvider indicates an expected call of UpdateModelProvider.
func (mr *MockModelProviderServiceClientMockRecorder) UpdateModelProvider(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateModelProvider", reflect.TypeOf((*MockModelProviderServiceClient)(nil).UpdateModelProvider), arg0, arg1)
}

// MockModelProviderServiceHandler is a mock of ModelProviderServiceHandler interface.
type MockModelProviderServiceHandler struct {
	ctrl     *gomock.Controller
	recorder *MockModelProviderServiceHandlerMockRecorder
	isgomock struct{}
}

// MockModelProviderServiceHandlerMockRecorder is the mock recorder for MockModelProviderServiceHandler.
type MockModelProviderServiceHandlerMockRecorder struct {
	mock *MockModelProviderServiceHandler
}

// NewMockModelProviderServiceHandler creates a new mock instance.
func NewMockModelProviderServiceHandler(ctrl *gomock.Controller) *MockModelProviderServiceHandler {
	mock := &MockModelProviderServiceHandler{ctrl: ctrl}
	mock.recorder = &MockModelProviderServiceHandlerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockModelProviderServiceHandler) EXPECT() *MockModelProviderServiceHandlerMockRecorder {
	return m.recorder
}

// CreateModelProvider mocks base method.
func (m *MockModelProviderServiceHandler) CreateModelProvider(arg0 context.Context, arg1 *connect.Request[v1.CreateModelProviderRequest]) (*connect.Response[v1.CreateModelProviderResponse], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateModelProvider", arg0, arg1)
	ret0, _ := ret[0].(*connect.Response[v1.CreateModelProviderResponse])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateModelProvider indicates an expected call of CreateModelProvider.
func (mr *MockModelProviderServiceHandlerMockRecorder) CreateModelProvider(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateModelProvider", reflect.TypeOf((*MockModelProviderServiceHandler)(nil).CreateModelProvider), arg0, arg1)
}

// DeleteModelProvider mocks base method.
func (m *MockModelProviderServiceHandler) DeleteModelProvider(arg0 context.Context, arg1 *connect.Request[v1.DeleteModelProviderRequest]) (*connect.Response[v1.DeleteModelProviderResponse], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteModelProvider", arg0, arg1)
	ret0, _ := ret[0].(*connect.Response[v1.DeleteModelProviderResponse])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteModelProvider indicates an expected call of DeleteModelProvider.
func (mr *MockModelProviderServiceHandlerMockRecorder) DeleteModelProvider(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteModelProvider", reflect.TypeOf((*MockModelProviderServiceHandler)(nil).DeleteModelProvider), arg0, arg1)
}

// GetModelProvider mocks base method.
func (m *MockModelProviderServiceHandler) GetModelProvider(arg0 context.Context, arg1 *connect.Request[v1.GetModelProviderRequest]) (*connect.Response[v1.GetModelProviderResponse], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetModelProvider", arg0, arg1)
	ret0, _ := ret[0].(*connect.Response[v1.GetModelProviderResponse])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetModelProvider indicates an expected call of GetModelProvider.
func (mr *MockModelProviderServiceHandlerMockRecorder) GetModelProvider(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetModelProvider", reflect.TypeOf((*MockModelProviderServiceHandler)(nil).GetModelProvider), arg0, arg1)
}

// ListModelProviders mocks base method.
func (m *MockModelProviderServiceHandler) ListModelProviders(arg0 context.Context, arg1 *connect.Request[v1.ListModelProvidersRequest]) (*connect.Response[v1.ListModelProvidersResponse], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListModelProviders", arg0, arg1)
	ret0, _ := ret[0].(*connect.Response[v1.ListModelProvidersResponse])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListModelProviders indicates an expected call of ListModelProviders.
func (mr *MockModelProviderServiceHandlerMockRecorder) ListModelProviders(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListModelProviders", reflect.TypeOf((*MockModelProviderServiceHandler)(nil).ListModelProviders), arg0, arg1)
}

// UpdateModelProvider mocks base method.
func (m *MockModelProviderServiceHandler) UpdateModelProvider(arg0 context.Context, arg1 *connect.Request[v1.UpdateModelProviderRequest]) (*connect.Response[v1.UpdateModelProviderResponse], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateModelProvider", arg0, arg1)
	ret0, _ := ret[0].(*connect.Response[v1.UpdateModelProviderResponse])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateModelProvider indicates an expected call of UpdateModelProvider.
func (mr *MockModelProviderServiceHandlerMockRecorder) UpdateModelProvider(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateModelProvider", reflect.TypeOf((*MockModelProviderServiceHandler)(nil).UpdateModelProvider), arg0, arg1)
}
