// Code generated by MockGen. DO NOT EDIT.
// Source: ../v1/v1connect/model.connect.go
//
// Generated by this command:
//
//	mockgen -source=../v1/v1connect/model.connect.go -destination=./test/model.connect_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	connect "connectrpc.com/connect"
	v1 "github.com/furisto/construct/api/go/v1"
	gomock "go.uber.org/mock/gomock"
)

// MockModelServiceClient is a mock of ModelServiceClient interface.
type MockModelServiceClient struct {
	ctrl     *gomock.Controller
	recorder *MockModelServiceClientMockRecorder
	isgomock struct{}
}

// MockModelServiceClientMockRecorder is the mock recorder for MockModelServiceClient.
type MockModelServiceClientMockRecorder struct {
	mock *MockModelServiceClient
}

// NewMockModelServiceClient creates a new mock instance.
func NewMockModelServiceClient(ctrl *gomock.Controller) *MockModelServiceClient {
	mock := &MockModelServiceClient{ctrl: ctrl}
	mock.recorder = &MockModelServiceClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockModelServiceClient) EXPECT() *MockModelServiceClientMockRecorder {
	return m.recorder
}

// CreateModel mocks base method.
func (m *MockModelServiceClient) CreateModel(arg0 context.Context, arg1 *connect.Request[v1.CreateModelRequest]) (*connect.Response[v1.CreateModelResponse], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateModel", arg0, arg1)
	ret0, _ := ret[0].(*connect.Response[v1.CreateModelResponse])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateModel indicates an expected call of CreateModel.
func (mr *MockModelServiceClientMockRecorder) CreateModel(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateModel", reflect.TypeOf((*MockModelServiceClient)(nil).CreateModel), arg0, arg1)
}

// DeleteModel mocks base method.
func (m *MockModelServiceClient) DeleteModel(arg0 context.Context, arg1 *connect.Request[v1.DeleteModelRequest]) (*connect.Response[v1.DeleteModelResponse], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteModel", arg0, arg1)
	ret0, _ := ret[0].(*connect.Response[v1.DeleteModelResponse])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteModel indicates an expected call of DeleteModel.
func (mr *MockModelServiceClientMockRecorder) DeleteModel(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteModel", reflect.TypeOf((*MockModelServiceClient)(nil).DeleteModel), arg0, arg1)
}

// GetModel mocks base method.
func (m *MockModelServiceClient) GetModel(arg0 context.Context, arg1 *connect.Request[v1.GetModelRequest]) (*connect.Response[v1.GetModelResponse], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetModel", arg0, arg1)
	ret0, _ := ret[0].(*connect.Response[v1.GetModelResponse])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetModel indicates an expected call of GetModel.
func (mr *MockModelServiceClientMockRecorder) GetModel(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetModel", reflect.TypeOf((*MockModelServiceClient)(nil).GetModel), arg0, arg1)
}

// ListModels mocks base method.
func (m *MockModelServiceClient) ListModels(arg0 context.Context, arg1 *connect.Request[v1.ListModelsRequest]) (*connect.Response[v1.ListModelsResponse], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListModels", arg0, arg1)
	ret0, _ := ret[0].(*connect.Response[v1.ListModelsResponse])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListModels indicates an expected call of ListModels.
func (mr *MockModelServiceClientMockRecorder) ListModels(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListModels", reflect.TypeOf((*MockModelServiceClient)(nil).ListModels), arg0, arg1)
}

// UpdateModel mocks base method.
func (m *MockModelServiceClient) UpdateModel(arg0 context.Context, arg1 *connect.Request[v1.UpdateModelRequest]) (*connect.Response[v1.UpdateModelResponse], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateModel", arg0, arg1)
	ret0, _ := ret[0].(*connect.Response[v1.UpdateModelResponse])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateModel indicates an expected call of UpdateModel.
func (mr *MockModelServiceClientMockRecorder) UpdateModel(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateModel", reflect.TypeOf((*MockModelServiceClient)(nil).UpdateModel), arg0, arg1)
}

// MockModelServiceHandler is a mock of ModelServiceHandler interface.
type MockModelServiceHandler struct {
	ctrl     *gomock.Controller
	recorder *MockModelServiceHandlerMockRecorder
	isgomock struct{}
}

// MockModelServiceHandlerMockRecorder is the mock recorder for MockModelServiceHandler.
type MockModelServiceHandlerMockRecorder struct {
	mock *MockModelServiceHandler
}

// NewMockModelServiceHandler creates a new mock instance.
func NewMockModelServiceHandler(ctrl *gomock.Controller) *MockModelServiceHandler {
	mock := &MockModelServiceHandler{ctrl: ctrl}
	mock.recorder = &MockModelServiceHandlerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockModelServiceHandler) EXPECT() *MockModelServiceHandlerMockRecorder {
	return m.recorder
}

// CreateModel mocks base method.
func (m *MockModelServiceHandler) CreateModel(arg0 context.Context, arg1 *connect.Request[v1.CreateModelRequest]) (*connect.Response[v1.CreateModelResponse], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateModel", arg0, arg1)
	ret0, _ := ret[0].(*connect.Response[v1.CreateModelResponse])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateModel indicates an expected call of CreateModel.
func (mr *MockModelServiceHandlerMockRecorder) CreateModel(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateModel", reflect.TypeOf((*MockModelServiceHandler)(nil).CreateModel), arg0, arg1)
}

// DeleteModel mocks base method.
func (m *MockModelServiceHandler) DeleteModel(arg0 context.Context, arg1 *connect.Request[v1.DeleteModelRequest]) (*connect.Response[v1.DeleteModelResponse], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteModel", arg0, arg1)
	ret0, _ := ret[0].(*connect.Response[v1.DeleteModelResponse])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteModel indicates an expected call of DeleteModel.
func (mr *MockModelServiceHandlerMockRecorder) DeleteModel(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteModel", reflect.TypeOf((*MockModelServiceHandler)(nil).DeleteModel), arg0, arg1)
}

// GetModel mocks base method.
func (m *MockModelServiceHandler) GetModel(arg0 context.Context, arg1 *connect.Request[v1.GetModelRequest]) (*connect.Response[v1.GetModelResponse], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetModel", arg0, arg1)
	ret0, _ := ret[0].(*connect.Response[v1.GetModelResponse])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetModel indicates an expected call of GetModel.
func (mr *MockModelServiceHandlerMockRecorder) GetModel(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetModel", reflect.TypeOf((*MockModelServiceHandler)(nil).GetModel), arg0, arg1)
}

// ListModels mocks base method.
func (m *MockModelServiceHandler) ListModels(arg0 context.Context, arg1 *connect.Request[v1.ListModelsRequest]) (*connect.Response[v1.ListModelsResponse], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListModels", arg0, arg1)
	ret0, _ := ret[0].(*connect.Response[v1.ListModelsResponse])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListModels indicates an expected call of ListModels.
func (mr *MockModelServiceHandlerMockRecorder) ListModels(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListModels", reflect.TypeOf((*MockModelServiceHandler)(nil).ListModels), arg0, arg1)
}

// UpdateModel mocks base method.
func (m *MockModelServiceHandler) UpdateModel(arg0 context.Context, arg1 *connect.Request[v1.UpdateModelRequest]) (*connect.Response[v1.UpdateModelResponse], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateModel", arg0, arg1)
	ret0, _ := ret[0].(*connect.Response[v1.UpdateModelResponse])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateModel indicates an expected call of UpdateModel.
func (mr *MockModelServiceHandlerMockRecorder) UpdateModel(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateModel", reflect.TypeOf((*MockModelServiceHandler)(nil).UpdateModel), arg0, arg1)
}
