// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/furisto/construct/shared (interfaces: UserInfo)
//
// Generated by this command:
//
//	mockgen -destination=frontend/cli/cmd/mocks/user_info_mock.go -package=mocks github.com/furisto/construct/shared UserInfo
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockUserInfo is a mock of UserInfo interface.
type MockUserInfo struct {
	ctrl     *gomock.Controller
	recorder *MockUserInfoMockRecorder
	isgomock struct{}
}

// MockUserInfoMockRecorder is the mock recorder for MockUserInfo.
type MockUserInfoMockRecorder struct {
	mock *MockUserInfo
}

// NewMockUserInfo creates a new mock instance.
func NewMockUserInfo(ctrl *gomock.Controller) *MockUserInfo {
	mock := &MockUserInfo{ctrl: ctrl}
	mock.recorder = &MockUserInfoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserInfo) EXPECT() *MockUserInfoMockRecorder {
	return m.recorder
}

// ConstructConfigDir mocks base method.
func (m *MockUserInfo) ConstructConfigDir() (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ConstructConfigDir")
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ConstructConfigDir indicates an expected call of ConstructConfigDir.
func (mr *MockUserInfoMockRecorder) ConstructConfigDir() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ConstructConfigDir", reflect.TypeOf((*MockUserInfo)(nil).ConstructConfigDir))
}

// ConstructDataDir mocks base method.
func (m *MockUserInfo) ConstructDataDir() (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ConstructDataDir")
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ConstructDataDir indicates an expected call of ConstructDataDir.
func (mr *MockUserInfoMockRecorder) ConstructDataDir() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ConstructDataDir", reflect.TypeOf((*MockUserInfo)(nil).ConstructDataDir))
}

// ConstructStateDir mocks base method.
func (m *MockUserInfo) ConstructStateDir() (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ConstructStateDir")
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ConstructStateDir indicates an expected call of ConstructStateDir.
func (mr *MockUserInfoMockRecorder) ConstructStateDir() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ConstructStateDir", reflect.TypeOf((*MockUserInfo)(nil).ConstructStateDir))
}

// Cwd mocks base method.
func (m *MockUserInfo) Cwd() (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Cwd")
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Cwd indicates an expected call of Cwd.
func (mr *MockUserInfoMockRecorder) Cwd() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Cwd", reflect.TypeOf((*MockUserInfo)(nil).Cwd))
}

// HomeDir mocks base method.
func (m *MockUserInfo) HomeDir() (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HomeDir")
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HomeDir indicates an expected call of HomeDir.
func (mr *MockUserInfoMockRecorder) HomeDir() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HomeDir", reflect.TypeOf((*MockUserInfo)(nil).HomeDir))
}

// UserID mocks base method.
func (m *MockUserInfo) UserID() (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UserID")
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UserID indicates an expected call of UserID.
func (mr *MockUserInfoMockRecorder) UserID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UserID", reflect.TypeOf((*MockUserInfo)(nil).UserID))
}
