// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: construct/v1/common.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SortField int32

const (
	// SORT_FIELD_UNSPECIFIED indicates no specific sort field is selected.
	SortField_SORT_FIELD_UNSPECIFIED SortField = 0
	// SORT_FIELD_NAME sorts results by the name field alphabetically.
	SortField_SORT_FIELD_NAME SortField = 1
	// SORT_FIELD_CREATED_AT sorts results by creation timestamp.
	SortField_SORT_FIELD_CREATED_AT SortField = 2
	// SORT_FIELD_UPDATED_AT sorts results by last modification timestamp.
	SortField_SORT_FIELD_UPDATED_AT SortField = 3
)

// Enum value maps for SortField.
var (
	SortField_name = map[int32]string{
		0: "SORT_FIELD_UNSPECIFIED",
		1: "SORT_FIELD_NAME",
		2: "SORT_FIELD_CREATED_AT",
		3: "SORT_FIELD_UPDATED_AT",
	}
	SortField_value = map[string]int32{
		"SORT_FIELD_UNSPECIFIED": 0,
		"SORT_FIELD_NAME":        1,
		"SORT_FIELD_CREATED_AT":  2,
		"SORT_FIELD_UPDATED_AT":  3,
	}
)

func (x SortField) Enum() *SortField {
	p := new(SortField)
	*p = x
	return p
}

func (x SortField) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SortField) Descriptor() protoreflect.EnumDescriptor {
	return file_construct_v1_common_proto_enumTypes[0].Descriptor()
}

func (SortField) Type() protoreflect.EnumType {
	return &file_construct_v1_common_proto_enumTypes[0]
}

func (x SortField) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SortField.Descriptor instead.
func (SortField) EnumDescriptor() ([]byte, []int) {
	return file_construct_v1_common_proto_rawDescGZIP(), []int{0}
}

// SortOrde specifies the direction for sorting results in list operations.
type SortOrder int32

const (
	// SORT_ORDER_UNSPECIFIED indicates no specific sort order is selected.
	SortOrder_SORT_ORDER_UNSPECIFIED SortOrder = 0
	// SORT_ORDER_ASC sorts results in ascending order (A-Z, oldest first).
	SortOrder_SORT_ORDER_ASC SortOrder = 1
	// SORT_ORDER_DESC sorts results in descending order (Z-A, newest first).
	SortOrder_SORT_ORDER_DESC SortOrder = 2
)

// Enum value maps for SortOrder.
var (
	SortOrder_name = map[int32]string{
		0: "SORT_ORDER_UNSPECIFIED",
		1: "SORT_ORDER_ASC",
		2: "SORT_ORDER_DESC",
	}
	SortOrder_value = map[string]int32{
		"SORT_ORDER_UNSPECIFIED": 0,
		"SORT_ORDER_ASC":         1,
		"SORT_ORDER_DESC":        2,
	}
)

func (x SortOrder) Enum() *SortOrder {
	p := new(SortOrder)
	*p = x
	return p
}

func (x SortOrder) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SortOrder) Descriptor() protoreflect.EnumDescriptor {
	return file_construct_v1_common_proto_enumTypes[1].Descriptor()
}

func (SortOrder) Type() protoreflect.EnumType {
	return &file_construct_v1_common_proto_enumTypes[1]
}

func (x SortOrder) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SortOrder.Descriptor instead.
func (SortOrder) EnumDescriptor() ([]byte, []int) {
	return file_construct_v1_common_proto_rawDescGZIP(), []int{1}
}

var File_construct_v1_common_proto protoreflect.FileDescriptor

const file_construct_v1_common_proto_rawDesc = "" +
	"\n" +
	"\x19construct/v1/common.proto\x12\fconstruct.v1*r\n" +
	"\tSortField\x12\x1a\n" +
	"\x16SORT_FIELD_UNSPECIFIED\x10\x00\x12\x13\n" +
	"\x0fSORT_FIELD_NAME\x10\x01\x12\x19\n" +
	"\x15SORT_FIELD_CREATED_AT\x10\x02\x12\x19\n" +
	"\x15SORT_FIELD_UPDATED_AT\x10\x03*P\n" +
	"\tSortOrder\x12\x1a\n" +
	"\x16SORT_ORDER_UNSPECIFIED\x10\x00\x12\x12\n" +
	"\x0eSORT_ORDER_ASC\x10\x01\x12\x13\n" +
	"\x0fSORT_ORDER_DESC\x10\x02B(Z&github.com/furisto/construct/api/go/v1b\x06proto3"

var (
	file_construct_v1_common_proto_rawDescOnce sync.Once
	file_construct_v1_common_proto_rawDescData []byte
)

func file_construct_v1_common_proto_rawDescGZIP() []byte {
	file_construct_v1_common_proto_rawDescOnce.Do(func() {
		file_construct_v1_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_construct_v1_common_proto_rawDesc), len(file_construct_v1_common_proto_rawDesc)))
	})
	return file_construct_v1_common_proto_rawDescData
}

var file_construct_v1_common_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_construct_v1_common_proto_goTypes = []any{
	(SortField)(0), // 0: construct.v1.SortField
	(SortOrder)(0), // 1: construct.v1.SortOrder
}
var file_construct_v1_common_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_construct_v1_common_proto_init() }
func file_construct_v1_common_proto_init() {
	if File_construct_v1_common_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_construct_v1_common_proto_rawDesc), len(file_construct_v1_common_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_construct_v1_common_proto_goTypes,
		DependencyIndexes: file_construct_v1_common_proto_depIdxs,
		EnumInfos:         file_construct_v1_common_proto_enumTypes,
	}.Build()
	File_construct_v1_common_proto = out.File
	file_construct_v1_common_proto_goTypes = nil
	file_construct_v1_common_proto_depIdxs = nil
}
