// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: construct/v1/model.proto

package v1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	decimal "google.golang.org/genproto/googleapis/type/decimal"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ModelCapability int32

const (
	ModelCapability_MODEL_CAPABILITY_UNSPECIFIED  ModelCapability = 0
	ModelCapability_MODEL_CAPABILITY_VISION       ModelCapability = 1
	ModelCapability_MODEL_CAPABILITY_COMPUTER_USE ModelCapability = 2
	ModelCapability_MODEL_CAPABILITY_PROMPT_CACHE ModelCapability = 3
	ModelCapability_MODEL_CAPABILITY_THINKING     ModelCapability = 4
)

// Enum value maps for ModelCapability.
var (
	ModelCapability_name = map[int32]string{
		0: "MODEL_CAPABILITY_UNSPECIFIED",
		1: "MODEL_CAPABILITY_VISION",
		2: "MODEL_CAPABILITY_COMPUTER_USE",
		3: "MODEL_CAPABILITY_PROMPT_CACHE",
		4: "MODEL_CAPABILITY_THINKING",
	}
	ModelCapability_value = map[string]int32{
		"MODEL_CAPABILITY_UNSPECIFIED":  0,
		"MODEL_CAPABILITY_VISION":       1,
		"MODEL_CAPABILITY_COMPUTER_USE": 2,
		"MODEL_CAPABILITY_PROMPT_CACHE": 3,
		"MODEL_CAPABILITY_THINKING":     4,
	}
)

func (x ModelCapability) Enum() *ModelCapability {
	p := new(ModelCapability)
	*p = x
	return p
}

func (x ModelCapability) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ModelCapability) Descriptor() protoreflect.EnumDescriptor {
	return file_construct_v1_model_proto_enumTypes[0].Descriptor()
}

func (ModelCapability) Type() protoreflect.EnumType {
	return &file_construct_v1_model_proto_enumTypes[0]
}

func (x ModelCapability) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ModelCapability.Descriptor instead.
func (ModelCapability) EnumDescriptor() ([]byte, []int) {
	return file_construct_v1_model_proto_rawDescGZIP(), []int{0}
}

type ModelMetadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ModelMetadata) Reset() {
	*x = ModelMetadata{}
	mi := &file_construct_v1_model_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModelMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModelMetadata) ProtoMessage() {}

func (x *ModelMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_construct_v1_model_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModelMetadata.ProtoReflect.Descriptor instead.
func (*ModelMetadata) Descriptor() ([]byte, []int) {
	return file_construct_v1_model_proto_rawDescGZIP(), []int{0}
}

func (x *ModelMetadata) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *ModelMetadata) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type ModelPricing struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	InputCost      *decimal.Decimal       `protobuf:"bytes,1,opt,name=input_cost,json=inputCost,proto3" json:"input_cost,omitempty"`
	OutputCost     *decimal.Decimal       `protobuf:"bytes,2,opt,name=output_cost,json=outputCost,proto3" json:"output_cost,omitempty"`
	CacheWriteCost *decimal.Decimal       `protobuf:"bytes,3,opt,name=cache_write_cost,json=cacheWriteCost,proto3" json:"cache_write_cost,omitempty"`
	CacheReadCost  *decimal.Decimal       `protobuf:"bytes,4,opt,name=cache_read_cost,json=cacheReadCost,proto3" json:"cache_read_cost,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ModelPricing) Reset() {
	*x = ModelPricing{}
	mi := &file_construct_v1_model_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModelPricing) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModelPricing) ProtoMessage() {}

func (x *ModelPricing) ProtoReflect() protoreflect.Message {
	mi := &file_construct_v1_model_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModelPricing.ProtoReflect.Descriptor instead.
func (*ModelPricing) Descriptor() ([]byte, []int) {
	return file_construct_v1_model_proto_rawDescGZIP(), []int{1}
}

func (x *ModelPricing) GetInputCost() *decimal.Decimal {
	if x != nil {
		return x.InputCost
	}
	return nil
}

func (x *ModelPricing) GetOutputCost() *decimal.Decimal {
	if x != nil {
		return x.OutputCost
	}
	return nil
}

func (x *ModelPricing) GetCacheWriteCost() *decimal.Decimal {
	if x != nil {
		return x.CacheWriteCost
	}
	return nil
}

func (x *ModelPricing) GetCacheReadCost() *decimal.Decimal {
	if x != nil {
		return x.CacheReadCost
	}
	return nil
}

type Model struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Metadata        *ModelMetadata         `protobuf:"bytes,2,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Name            string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	DisplayName     *string                `protobuf:"bytes,4,opt,name=display_name,json=displayName,proto3,oneof" json:"display_name,omitempty"`
	ModelProviderId string                 `protobuf:"bytes,5,opt,name=model_provider_id,json=modelProviderId,proto3" json:"model_provider_id,omitempty"`
	Capabilities    []ModelCapability      `protobuf:"varint,6,rep,packed,name=capabilities,proto3,enum=construct.v1.ModelCapability" json:"capabilities,omitempty"`
	Pricing         *ModelPricing          `protobuf:"bytes,7,opt,name=pricing,proto3" json:"pricing,omitempty"`
	ContextWindow   int64                  `protobuf:"varint,8,opt,name=context_window,json=contextWindow,proto3" json:"context_window,omitempty"`
	Enabled         bool                   `protobuf:"varint,9,opt,name=enabled,proto3" json:"enabled,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Model) Reset() {
	*x = Model{}
	mi := &file_construct_v1_model_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Model) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Model) ProtoMessage() {}

func (x *Model) ProtoReflect() protoreflect.Message {
	mi := &file_construct_v1_model_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Model.ProtoReflect.Descriptor instead.
func (*Model) Descriptor() ([]byte, []int) {
	return file_construct_v1_model_proto_rawDescGZIP(), []int{2}
}

func (x *Model) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Model) GetMetadata() *ModelMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *Model) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Model) GetDisplayName() string {
	if x != nil && x.DisplayName != nil {
		return *x.DisplayName
	}
	return ""
}

func (x *Model) GetModelProviderId() string {
	if x != nil {
		return x.ModelProviderId
	}
	return ""
}

func (x *Model) GetCapabilities() []ModelCapability {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

func (x *Model) GetPricing() *ModelPricing {
	if x != nil {
		return x.Pricing
	}
	return nil
}

func (x *Model) GetContextWindow() int64 {
	if x != nil {
		return x.ContextWindow
	}
	return 0
}

func (x *Model) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

type CreateModelRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Name            string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	DisplayName     *string                `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3,oneof" json:"display_name,omitempty"`
	ModelProviderId string                 `protobuf:"bytes,3,opt,name=model_provider_id,json=modelProviderId,proto3" json:"model_provider_id,omitempty"`
	Capabilities    []ModelCapability      `protobuf:"varint,4,rep,packed,name=capabilities,proto3,enum=construct.v1.ModelCapability" json:"capabilities,omitempty"`
	Pricing         *ModelPricing          `protobuf:"bytes,5,opt,name=pricing,proto3" json:"pricing,omitempty"`
	ContextWindow   int64                  `protobuf:"varint,6,opt,name=context_window,json=contextWindow,proto3" json:"context_window,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CreateModelRequest) Reset() {
	*x = CreateModelRequest{}
	mi := &file_construct_v1_model_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateModelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateModelRequest) ProtoMessage() {}

func (x *CreateModelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_construct_v1_model_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateModelRequest.ProtoReflect.Descriptor instead.
func (*CreateModelRequest) Descriptor() ([]byte, []int) {
	return file_construct_v1_model_proto_rawDescGZIP(), []int{3}
}

func (x *CreateModelRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateModelRequest) GetDisplayName() string {
	if x != nil && x.DisplayName != nil {
		return *x.DisplayName
	}
	return ""
}

func (x *CreateModelRequest) GetModelProviderId() string {
	if x != nil {
		return x.ModelProviderId
	}
	return ""
}

func (x *CreateModelRequest) GetCapabilities() []ModelCapability {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

func (x *CreateModelRequest) GetPricing() *ModelPricing {
	if x != nil {
		return x.Pricing
	}
	return nil
}

func (x *CreateModelRequest) GetContextWindow() int64 {
	if x != nil {
		return x.ContextWindow
	}
	return 0
}

type CreateModelResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Model         *Model                 `protobuf:"bytes,1,opt,name=model,proto3" json:"model,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateModelResponse) Reset() {
	*x = CreateModelResponse{}
	mi := &file_construct_v1_model_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateModelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateModelResponse) ProtoMessage() {}

func (x *CreateModelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_construct_v1_model_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateModelResponse.ProtoReflect.Descriptor instead.
func (*CreateModelResponse) Descriptor() ([]byte, []int) {
	return file_construct_v1_model_proto_rawDescGZIP(), []int{4}
}

func (x *CreateModelResponse) GetModel() *Model {
	if x != nil {
		return x.Model
	}
	return nil
}

type GetModelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetModelRequest) Reset() {
	*x = GetModelRequest{}
	mi := &file_construct_v1_model_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetModelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetModelRequest) ProtoMessage() {}

func (x *GetModelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_construct_v1_model_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetModelRequest.ProtoReflect.Descriptor instead.
func (*GetModelRequest) Descriptor() ([]byte, []int) {
	return file_construct_v1_model_proto_rawDescGZIP(), []int{5}
}

func (x *GetModelRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetModelResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Model         *Model                 `protobuf:"bytes,1,opt,name=model,proto3" json:"model,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetModelResponse) Reset() {
	*x = GetModelResponse{}
	mi := &file_construct_v1_model_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetModelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetModelResponse) ProtoMessage() {}

func (x *GetModelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_construct_v1_model_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetModelResponse.ProtoReflect.Descriptor instead.
func (*GetModelResponse) Descriptor() ([]byte, []int) {
	return file_construct_v1_model_proto_rawDescGZIP(), []int{6}
}

func (x *GetModelResponse) GetModel() *Model {
	if x != nil {
		return x.Model
	}
	return nil
}

type ListModelsRequest struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Filter        *ListModelsRequest_Filter `protobuf:"bytes,1,opt,name=filter,proto3" json:"filter,omitempty"`
	PageToken     string                    `protobuf:"bytes,2,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListModelsRequest) Reset() {
	*x = ListModelsRequest{}
	mi := &file_construct_v1_model_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListModelsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListModelsRequest) ProtoMessage() {}

func (x *ListModelsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_construct_v1_model_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListModelsRequest.ProtoReflect.Descriptor instead.
func (*ListModelsRequest) Descriptor() ([]byte, []int) {
	return file_construct_v1_model_proto_rawDescGZIP(), []int{7}
}

func (x *ListModelsRequest) GetFilter() *ListModelsRequest_Filter {
	if x != nil {
		return x.Filter
	}
	return nil
}

func (x *ListModelsRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

type ListModelsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Models        []*Model               `protobuf:"bytes,1,rep,name=models,proto3" json:"models,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListModelsResponse) Reset() {
	*x = ListModelsResponse{}
	mi := &file_construct_v1_model_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListModelsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListModelsResponse) ProtoMessage() {}

func (x *ListModelsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_construct_v1_model_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListModelsResponse.ProtoReflect.Descriptor instead.
func (*ListModelsResponse) Descriptor() ([]byte, []int) {
	return file_construct_v1_model_proto_rawDescGZIP(), []int{8}
}

func (x *ListModelsResponse) GetModels() []*Model {
	if x != nil {
		return x.Models
	}
	return nil
}

func (x *ListModelsResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

type UpdateModelRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name            *string                `protobuf:"bytes,2,opt,name=name,proto3,oneof" json:"name,omitempty"`
	DisplayName     *string                `protobuf:"bytes,3,opt,name=display_name,json=displayName,proto3,oneof" json:"display_name,omitempty"`
	ModelProviderId *string                `protobuf:"bytes,4,opt,name=model_provider_id,json=modelProviderId,proto3,oneof" json:"model_provider_id,omitempty"`
	Capabilities    []ModelCapability      `protobuf:"varint,5,rep,packed,name=capabilities,proto3,enum=construct.v1.ModelCapability" json:"capabilities,omitempty"`
	Pricing         *ModelPricing          `protobuf:"bytes,6,opt,name=pricing,proto3,oneof" json:"pricing,omitempty"`
	ContextWindow   *int64                 `protobuf:"varint,7,opt,name=context_window,json=contextWindow,proto3,oneof" json:"context_window,omitempty"`
	Enabled         *bool                  `protobuf:"varint,8,opt,name=enabled,proto3,oneof" json:"enabled,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *UpdateModelRequest) Reset() {
	*x = UpdateModelRequest{}
	mi := &file_construct_v1_model_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateModelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateModelRequest) ProtoMessage() {}

func (x *UpdateModelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_construct_v1_model_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateModelRequest.ProtoReflect.Descriptor instead.
func (*UpdateModelRequest) Descriptor() ([]byte, []int) {
	return file_construct_v1_model_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateModelRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateModelRequest) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *UpdateModelRequest) GetDisplayName() string {
	if x != nil && x.DisplayName != nil {
		return *x.DisplayName
	}
	return ""
}

func (x *UpdateModelRequest) GetModelProviderId() string {
	if x != nil && x.ModelProviderId != nil {
		return *x.ModelProviderId
	}
	return ""
}

func (x *UpdateModelRequest) GetCapabilities() []ModelCapability {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

func (x *UpdateModelRequest) GetPricing() *ModelPricing {
	if x != nil {
		return x.Pricing
	}
	return nil
}

func (x *UpdateModelRequest) GetContextWindow() int64 {
	if x != nil && x.ContextWindow != nil {
		return *x.ContextWindow
	}
	return 0
}

func (x *UpdateModelRequest) GetEnabled() bool {
	if x != nil && x.Enabled != nil {
		return *x.Enabled
	}
	return false
}

type UpdateModelResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Model         *Model                 `protobuf:"bytes,1,opt,name=model,proto3" json:"model,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateModelResponse) Reset() {
	*x = UpdateModelResponse{}
	mi := &file_construct_v1_model_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateModelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateModelResponse) ProtoMessage() {}

func (x *UpdateModelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_construct_v1_model_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateModelResponse.ProtoReflect.Descriptor instead.
func (*UpdateModelResponse) Descriptor() ([]byte, []int) {
	return file_construct_v1_model_proto_rawDescGZIP(), []int{10}
}

func (x *UpdateModelResponse) GetModel() *Model {
	if x != nil {
		return x.Model
	}
	return nil
}

type DeleteModelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteModelRequest) Reset() {
	*x = DeleteModelRequest{}
	mi := &file_construct_v1_model_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteModelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteModelRequest) ProtoMessage() {}

func (x *DeleteModelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_construct_v1_model_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteModelRequest.ProtoReflect.Descriptor instead.
func (*DeleteModelRequest) Descriptor() ([]byte, []int) {
	return file_construct_v1_model_proto_rawDescGZIP(), []int{11}
}

func (x *DeleteModelRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteModelResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteModelResponse) Reset() {
	*x = DeleteModelResponse{}
	mi := &file_construct_v1_model_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteModelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteModelResponse) ProtoMessage() {}

func (x *DeleteModelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_construct_v1_model_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteModelResponse.ProtoReflect.Descriptor instead.
func (*DeleteModelResponse) Descriptor() ([]byte, []int) {
	return file_construct_v1_model_proto_rawDescGZIP(), []int{12}
}

type ListModelsRequest_Filter struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ModelProviderId *string                `protobuf:"bytes,1,opt,name=model_provider_id,json=modelProviderId,proto3,oneof" json:"model_provider_id,omitempty"`
	Enabled         *bool                  `protobuf:"varint,2,opt,name=enabled,proto3,oneof" json:"enabled,omitempty"`
	Name            *string                `protobuf:"bytes,3,opt,name=name,proto3,oneof" json:"name,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ListModelsRequest_Filter) Reset() {
	*x = ListModelsRequest_Filter{}
	mi := &file_construct_v1_model_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListModelsRequest_Filter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListModelsRequest_Filter) ProtoMessage() {}

func (x *ListModelsRequest_Filter) ProtoReflect() protoreflect.Message {
	mi := &file_construct_v1_model_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListModelsRequest_Filter.ProtoReflect.Descriptor instead.
func (*ListModelsRequest_Filter) Descriptor() ([]byte, []int) {
	return file_construct_v1_model_proto_rawDescGZIP(), []int{7, 0}
}

func (x *ListModelsRequest_Filter) GetModelProviderId() string {
	if x != nil && x.ModelProviderId != nil {
		return *x.ModelProviderId
	}
	return ""
}

func (x *ListModelsRequest_Filter) GetEnabled() bool {
	if x != nil && x.Enabled != nil {
		return *x.Enabled
	}
	return false
}

func (x *ListModelsRequest_Filter) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

var File_construct_v1_model_proto protoreflect.FileDescriptor

const file_construct_v1_model_proto_rawDesc = "" +
	"\n" +
	"\x18construct/v1/model.proto\x12\fconstruct.v1\x1a\x1bbuf/validate/validate.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x19google/type/decimal.proto\"\x95\x01\n" +
	"\rModelMetadata\x12A\n" +
	"\n" +
	"created_at\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampB\x06\xbaH\x03\xc8\x01\x01R\tcreatedAt\x12A\n" +
	"\n" +
	"updated_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampB\x06\xbaH\x03\xc8\x01\x01R\tupdatedAt\"\xf8\x01\n" +
	"\fModelPricing\x123\n" +
	"\n" +
	"input_cost\x18\x01 \x01(\v2\x14.google.type.DecimalR\tinputCost\x125\n" +
	"\voutput_cost\x18\x02 \x01(\v2\x14.google.type.DecimalR\n" +
	"outputCost\x12>\n" +
	"\x10cache_write_cost\x18\x03 \x01(\v2\x14.google.type.DecimalR\x0ecacheWriteCost\x12<\n" +
	"\x0fcache_read_cost\x18\x04 \x01(\v2\x14.google.type.DecimalR\rcacheReadCost\"\xac\x03\n" +
	"\x05Model\x12\x18\n" +
	"\x02id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\x02id\x127\n" +
	"\bmetadata\x18\x02 \x01(\v2\x1b.construct.v1.ModelMetadataR\bmetadata\x12\x1e\n" +
	"\x04name\x18\x03 \x01(\tB\n" +
	"\xbaH\ar\x05\x10\x01\x18\xff\x01R\x04name\x12&\n" +
	"\fdisplay_name\x18\x04 \x01(\tH\x00R\vdisplayName\x88\x01\x01\x124\n" +
	"\x11model_provider_id\x18\x05 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\x0fmodelProviderId\x12A\n" +
	"\fcapabilities\x18\x06 \x03(\x0e2\x1d.construct.v1.ModelCapabilityR\fcapabilities\x124\n" +
	"\apricing\x18\a \x01(\v2\x1a.construct.v1.ModelPricingR\apricing\x12.\n" +
	"\x0econtext_window\x18\b \x01(\x03B\a\xbaH\x04\"\x02 \x00R\rcontextWindow\x12\x18\n" +
	"\aenabled\x18\t \x01(\bR\aenabledB\x0f\n" +
	"\r_display_name\"\xd6\x02\n" +
	"\x12CreateModelRequest\x12\x1e\n" +
	"\x04name\x18\x01 \x01(\tB\n" +
	"\xbaH\ar\x05\x10\x01\x18\xff\x01R\x04name\x120\n" +
	"\fdisplay_name\x18\x02 \x01(\tB\b\xbaH\x05r\x03\x18\xff\x01H\x00R\vdisplayName\x88\x01\x01\x124\n" +
	"\x11model_provider_id\x18\x03 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\x0fmodelProviderId\x12A\n" +
	"\fcapabilities\x18\x04 \x03(\x0e2\x1d.construct.v1.ModelCapabilityR\fcapabilities\x124\n" +
	"\apricing\x18\x05 \x01(\v2\x1a.construct.v1.ModelPricingR\apricing\x12.\n" +
	"\x0econtext_window\x18\x06 \x01(\x03B\a\xbaH\x04\"\x02 \x00R\rcontextWindowB\x0f\n" +
	"\r_display_name\"H\n" +
	"\x13CreateModelResponse\x121\n" +
	"\x05model\x18\x01 \x01(\v2\x13.construct.v1.ModelB\x06\xbaH\x03\xc8\x01\x01R\x05model\"+\n" +
	"\x0fGetModelRequest\x12\x18\n" +
	"\x02id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\x02id\"E\n" +
	"\x10GetModelResponse\x121\n" +
	"\x05model\x18\x01 \x01(\v2\x13.construct.v1.ModelB\x06\xbaH\x03\xc8\x01\x01R\x05model\"\xb1\x02\n" +
	"\x11ListModelsRequest\x12>\n" +
	"\x06filter\x18\x01 \x01(\v2&.construct.v1.ListModelsRequest.FilterR\x06filter\x12'\n" +
	"\n" +
	"page_token\x18\x02 \x01(\tB\b\xbaH\x05r\x03\x18\xff\x01R\tpageToken\x1a\xb2\x01\n" +
	"\x06Filter\x129\n" +
	"\x11model_provider_id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01H\x00R\x0fmodelProviderId\x88\x01\x01\x12\x1d\n" +
	"\aenabled\x18\x02 \x01(\bH\x01R\aenabled\x88\x01\x01\x12#\n" +
	"\x04name\x18\x03 \x01(\tB\n" +
	"\xbaH\ar\x05\x10\x01\x18\xff\x01H\x02R\x04name\x88\x01\x01B\x14\n" +
	"\x12_model_provider_idB\n" +
	"\n" +
	"\b_enabledB\a\n" +
	"\x05_name\"i\n" +
	"\x12ListModelsResponse\x12+\n" +
	"\x06models\x18\x01 \x03(\v2\x13.construct.v1.ModelR\x06models\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"\xed\x03\n" +
	"\x12UpdateModelRequest\x12\x18\n" +
	"\x02id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\x02id\x12#\n" +
	"\x04name\x18\x02 \x01(\tB\n" +
	"\xbaH\ar\x05\x10\x01\x18\xff\x01H\x00R\x04name\x88\x01\x01\x120\n" +
	"\fdisplay_name\x18\x03 \x01(\tB\b\xbaH\x05r\x03\x18\xff\x01H\x01R\vdisplayName\x88\x01\x01\x129\n" +
	"\x11model_provider_id\x18\x04 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01H\x02R\x0fmodelProviderId\x88\x01\x01\x12A\n" +
	"\fcapabilities\x18\x05 \x03(\x0e2\x1d.construct.v1.ModelCapabilityR\fcapabilities\x129\n" +
	"\apricing\x18\x06 \x01(\v2\x1a.construct.v1.ModelPricingH\x03R\apricing\x88\x01\x01\x123\n" +
	"\x0econtext_window\x18\a \x01(\x03B\a\xbaH\x04\"\x02 \x00H\x04R\rcontextWindow\x88\x01\x01\x12\x1d\n" +
	"\aenabled\x18\b \x01(\bH\x05R\aenabled\x88\x01\x01B\a\n" +
	"\x05_nameB\x0f\n" +
	"\r_display_nameB\x14\n" +
	"\x12_model_provider_idB\n" +
	"\n" +
	"\b_pricingB\x11\n" +
	"\x0f_context_windowB\n" +
	"\n" +
	"\b_enabled\"H\n" +
	"\x13UpdateModelResponse\x121\n" +
	"\x05model\x18\x01 \x01(\v2\x13.construct.v1.ModelB\x06\xbaH\x03\xc8\x01\x01R\x05model\".\n" +
	"\x12DeleteModelRequest\x12\x18\n" +
	"\x02id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\x02id\"\x15\n" +
	"\x13DeleteModelResponse*\xb5\x01\n" +
	"\x0fModelCapability\x12 \n" +
	"\x1cMODEL_CAPABILITY_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17MODEL_CAPABILITY_VISION\x10\x01\x12!\n" +
	"\x1dMODEL_CAPABILITY_COMPUTER_USE\x10\x02\x12!\n" +
	"\x1dMODEL_CAPABILITY_PROMPT_CACHE\x10\x03\x12\x1d\n" +
	"\x19MODEL_CAPABILITY_THINKING\x10\x042\xb6\x03\n" +
	"\fModelService\x12T\n" +
	"\vCreateModel\x12 .construct.v1.CreateModelRequest\x1a!.construct.v1.CreateModelResponse\"\x00\x12N\n" +
	"\bGetModel\x12\x1d.construct.v1.GetModelRequest\x1a\x1e.construct.v1.GetModelResponse\"\x03\x90\x02\x01\x12T\n" +
	"\n" +
	"ListModels\x12\x1f.construct.v1.ListModelsRequest\x1a .construct.v1.ListModelsResponse\"\x03\x90\x02\x01\x12T\n" +
	"\vUpdateModel\x12 .construct.v1.UpdateModelRequest\x1a!.construct.v1.UpdateModelResponse\"\x00\x12T\n" +
	"\vDeleteModel\x12 .construct.v1.DeleteModelRequest\x1a!.construct.v1.DeleteModelResponse\"\x00B(Z&github.com/furisto/construct/api/go/v1b\x06proto3"

var (
	file_construct_v1_model_proto_rawDescOnce sync.Once
	file_construct_v1_model_proto_rawDescData []byte
)

func file_construct_v1_model_proto_rawDescGZIP() []byte {
	file_construct_v1_model_proto_rawDescOnce.Do(func() {
		file_construct_v1_model_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_construct_v1_model_proto_rawDesc), len(file_construct_v1_model_proto_rawDesc)))
	})
	return file_construct_v1_model_proto_rawDescData
}

var file_construct_v1_model_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_construct_v1_model_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_construct_v1_model_proto_goTypes = []any{
	(ModelCapability)(0),             // 0: construct.v1.ModelCapability
	(*ModelMetadata)(nil),            // 1: construct.v1.ModelMetadata
	(*ModelPricing)(nil),             // 2: construct.v1.ModelPricing
	(*Model)(nil),                    // 3: construct.v1.Model
	(*CreateModelRequest)(nil),       // 4: construct.v1.CreateModelRequest
	(*CreateModelResponse)(nil),      // 5: construct.v1.CreateModelResponse
	(*GetModelRequest)(nil),          // 6: construct.v1.GetModelRequest
	(*GetModelResponse)(nil),         // 7: construct.v1.GetModelResponse
	(*ListModelsRequest)(nil),        // 8: construct.v1.ListModelsRequest
	(*ListModelsResponse)(nil),       // 9: construct.v1.ListModelsResponse
	(*UpdateModelRequest)(nil),       // 10: construct.v1.UpdateModelRequest
	(*UpdateModelResponse)(nil),      // 11: construct.v1.UpdateModelResponse
	(*DeleteModelRequest)(nil),       // 12: construct.v1.DeleteModelRequest
	(*DeleteModelResponse)(nil),      // 13: construct.v1.DeleteModelResponse
	(*ListModelsRequest_Filter)(nil), // 14: construct.v1.ListModelsRequest.Filter
	(*timestamppb.Timestamp)(nil),    // 15: google.protobuf.Timestamp
	(*decimal.Decimal)(nil),          // 16: google.type.Decimal
}
var file_construct_v1_model_proto_depIdxs = []int32{
	15, // 0: construct.v1.ModelMetadata.created_at:type_name -> google.protobuf.Timestamp
	15, // 1: construct.v1.ModelMetadata.updated_at:type_name -> google.protobuf.Timestamp
	16, // 2: construct.v1.ModelPricing.input_cost:type_name -> google.type.Decimal
	16, // 3: construct.v1.ModelPricing.output_cost:type_name -> google.type.Decimal
	16, // 4: construct.v1.ModelPricing.cache_write_cost:type_name -> google.type.Decimal
	16, // 5: construct.v1.ModelPricing.cache_read_cost:type_name -> google.type.Decimal
	1,  // 6: construct.v1.Model.metadata:type_name -> construct.v1.ModelMetadata
	0,  // 7: construct.v1.Model.capabilities:type_name -> construct.v1.ModelCapability
	2,  // 8: construct.v1.Model.pricing:type_name -> construct.v1.ModelPricing
	0,  // 9: construct.v1.CreateModelRequest.capabilities:type_name -> construct.v1.ModelCapability
	2,  // 10: construct.v1.CreateModelRequest.pricing:type_name -> construct.v1.ModelPricing
	3,  // 11: construct.v1.CreateModelResponse.model:type_name -> construct.v1.Model
	3,  // 12: construct.v1.GetModelResponse.model:type_name -> construct.v1.Model
	14, // 13: construct.v1.ListModelsRequest.filter:type_name -> construct.v1.ListModelsRequest.Filter
	3,  // 14: construct.v1.ListModelsResponse.models:type_name -> construct.v1.Model
	0,  // 15: construct.v1.UpdateModelRequest.capabilities:type_name -> construct.v1.ModelCapability
	2,  // 16: construct.v1.UpdateModelRequest.pricing:type_name -> construct.v1.ModelPricing
	3,  // 17: construct.v1.UpdateModelResponse.model:type_name -> construct.v1.Model
	4,  // 18: construct.v1.ModelService.CreateModel:input_type -> construct.v1.CreateModelRequest
	6,  // 19: construct.v1.ModelService.GetModel:input_type -> construct.v1.GetModelRequest
	8,  // 20: construct.v1.ModelService.ListModels:input_type -> construct.v1.ListModelsRequest
	10, // 21: construct.v1.ModelService.UpdateModel:input_type -> construct.v1.UpdateModelRequest
	12, // 22: construct.v1.ModelService.DeleteModel:input_type -> construct.v1.DeleteModelRequest
	5,  // 23: construct.v1.ModelService.CreateModel:output_type -> construct.v1.CreateModelResponse
	7,  // 24: construct.v1.ModelService.GetModel:output_type -> construct.v1.GetModelResponse
	9,  // 25: construct.v1.ModelService.ListModels:output_type -> construct.v1.ListModelsResponse
	11, // 26: construct.v1.ModelService.UpdateModel:output_type -> construct.v1.UpdateModelResponse
	13, // 27: construct.v1.ModelService.DeleteModel:output_type -> construct.v1.DeleteModelResponse
	23, // [23:28] is the sub-list for method output_type
	18, // [18:23] is the sub-list for method input_type
	18, // [18:18] is the sub-list for extension type_name
	18, // [18:18] is the sub-list for extension extendee
	0,  // [0:18] is the sub-list for field type_name
}

func init() { file_construct_v1_model_proto_init() }
func file_construct_v1_model_proto_init() {
	if File_construct_v1_model_proto != nil {
		return
	}
	file_construct_v1_model_proto_msgTypes[2].OneofWrappers = []any{}
	file_construct_v1_model_proto_msgTypes[3].OneofWrappers = []any{}
	file_construct_v1_model_proto_msgTypes[9].OneofWrappers = []any{}
	file_construct_v1_model_proto_msgTypes[13].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_construct_v1_model_proto_rawDesc), len(file_construct_v1_model_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_construct_v1_model_proto_goTypes,
		DependencyIndexes: file_construct_v1_model_proto_depIdxs,
		EnumInfos:         file_construct_v1_model_proto_enumTypes,
		MessageInfos:      file_construct_v1_model_proto_msgTypes,
	}.Build()
	File_construct_v1_model_proto = out.File
	file_construct_v1_model_proto_goTypes = nil
	file_construct_v1_model_proto_depIdxs = nil
}
