// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: construct/v1/modelprovider.proto

package v1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ModelProviderType int32

const (
	ModelProviderType_MODEL_PROVIDER_TYPE_UNSPECIFIED ModelProviderType = 0
	ModelProviderType_MODEL_PROVIDER_TYPE_ANTHROPIC   ModelProviderType = 1
	ModelProviderType_MODEL_PROVIDER_TYPE_OPENAI      ModelProviderType = 2
)

// Enum value maps for ModelProviderType.
var (
	ModelProviderType_name = map[int32]string{
		0: "MODEL_PROVIDER_TYPE_UNSPECIFIED",
		1: "MODEL_PROVIDER_TYPE_ANTHROPIC",
		2: "MODEL_PROVIDER_TYPE_OPENAI",
	}
	ModelProviderType_value = map[string]int32{
		"MODEL_PROVIDER_TYPE_UNSPECIFIED": 0,
		"MODEL_PROVIDER_TYPE_ANTHROPIC":   1,
		"MODEL_PROVIDER_TYPE_OPENAI":      2,
	}
)

func (x ModelProviderType) Enum() *ModelProviderType {
	p := new(ModelProviderType)
	*p = x
	return p
}

func (x ModelProviderType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ModelProviderType) Descriptor() protoreflect.EnumDescriptor {
	return file_construct_v1_modelprovider_proto_enumTypes[0].Descriptor()
}

func (ModelProviderType) Type() protoreflect.EnumType {
	return &file_construct_v1_modelprovider_proto_enumTypes[0]
}

func (x ModelProviderType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ModelProviderType.Descriptor instead.
func (ModelProviderType) EnumDescriptor() ([]byte, []int) {
	return file_construct_v1_modelprovider_proto_rawDescGZIP(), []int{0}
}

type CreateModelProviderRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Name  string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Types that are valid to be assigned to Authentication:
	//
	//	*CreateModelProviderRequest_ApiKey
	Authentication isCreateModelProviderRequest_Authentication `protobuf_oneof:"authentication"`
	ProviderType   ModelProviderType                           `protobuf:"varint,30,opt,name=provider_type,json=providerType,proto3,enum=construct.v1.ModelProviderType" json:"provider_type,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateModelProviderRequest) Reset() {
	*x = CreateModelProviderRequest{}
	mi := &file_construct_v1_modelprovider_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateModelProviderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateModelProviderRequest) ProtoMessage() {}

func (x *CreateModelProviderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_construct_v1_modelprovider_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateModelProviderRequest.ProtoReflect.Descriptor instead.
func (*CreateModelProviderRequest) Descriptor() ([]byte, []int) {
	return file_construct_v1_modelprovider_proto_rawDescGZIP(), []int{0}
}

func (x *CreateModelProviderRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateModelProviderRequest) GetAuthentication() isCreateModelProviderRequest_Authentication {
	if x != nil {
		return x.Authentication
	}
	return nil
}

func (x *CreateModelProviderRequest) GetApiKey() string {
	if x != nil {
		if x, ok := x.Authentication.(*CreateModelProviderRequest_ApiKey); ok {
			return x.ApiKey
		}
	}
	return ""
}

func (x *CreateModelProviderRequest) GetProviderType() ModelProviderType {
	if x != nil {
		return x.ProviderType
	}
	return ModelProviderType_MODEL_PROVIDER_TYPE_UNSPECIFIED
}

type isCreateModelProviderRequest_Authentication interface {
	isCreateModelProviderRequest_Authentication()
}

type CreateModelProviderRequest_ApiKey struct {
	ApiKey string `protobuf:"bytes,2,opt,name=api_key,json=apiKey,proto3,oneof"`
}

func (*CreateModelProviderRequest_ApiKey) isCreateModelProviderRequest_Authentication() {}

type CreateModelProviderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ModelProvider *ModelProvider         `protobuf:"bytes,1,opt,name=model_provider,json=modelProvider,proto3" json:"model_provider,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateModelProviderResponse) Reset() {
	*x = CreateModelProviderResponse{}
	mi := &file_construct_v1_modelprovider_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateModelProviderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateModelProviderResponse) ProtoMessage() {}

func (x *CreateModelProviderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_construct_v1_modelprovider_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateModelProviderResponse.ProtoReflect.Descriptor instead.
func (*CreateModelProviderResponse) Descriptor() ([]byte, []int) {
	return file_construct_v1_modelprovider_proto_rawDescGZIP(), []int{1}
}

func (x *CreateModelProviderResponse) GetModelProvider() *ModelProvider {
	if x != nil {
		return x.ModelProvider
	}
	return nil
}

type ModelProvider struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	ProviderType  ModelProviderType      `protobuf:"varint,3,opt,name=provider_type,json=providerType,proto3,enum=construct.v1.ModelProviderType" json:"provider_type,omitempty"`
	Enabled       bool                   `protobuf:"varint,4,opt,name=enabled,proto3" json:"enabled,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ModelProvider) Reset() {
	*x = ModelProvider{}
	mi := &file_construct_v1_modelprovider_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModelProvider) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModelProvider) ProtoMessage() {}

func (x *ModelProvider) ProtoReflect() protoreflect.Message {
	mi := &file_construct_v1_modelprovider_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModelProvider.ProtoReflect.Descriptor instead.
func (*ModelProvider) Descriptor() ([]byte, []int) {
	return file_construct_v1_modelprovider_proto_rawDescGZIP(), []int{2}
}

func (x *ModelProvider) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ModelProvider) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ModelProvider) GetProviderType() ModelProviderType {
	if x != nil {
		return x.ProviderType
	}
	return ModelProviderType_MODEL_PROVIDER_TYPE_UNSPECIFIED
}

func (x *ModelProvider) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *ModelProvider) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *ModelProvider) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type GetModelProviderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetModelProviderRequest) Reset() {
	*x = GetModelProviderRequest{}
	mi := &file_construct_v1_modelprovider_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetModelProviderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetModelProviderRequest) ProtoMessage() {}

func (x *GetModelProviderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_construct_v1_modelprovider_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetModelProviderRequest.ProtoReflect.Descriptor instead.
func (*GetModelProviderRequest) Descriptor() ([]byte, []int) {
	return file_construct_v1_modelprovider_proto_rawDescGZIP(), []int{3}
}

func (x *GetModelProviderRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetModelProviderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ModelProvider *ModelProvider         `protobuf:"bytes,1,opt,name=model_provider,json=modelProvider,proto3" json:"model_provider,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetModelProviderResponse) Reset() {
	*x = GetModelProviderResponse{}
	mi := &file_construct_v1_modelprovider_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetModelProviderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetModelProviderResponse) ProtoMessage() {}

func (x *GetModelProviderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_construct_v1_modelprovider_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetModelProviderResponse.ProtoReflect.Descriptor instead.
func (*GetModelProviderResponse) Descriptor() ([]byte, []int) {
	return file_construct_v1_modelprovider_proto_rawDescGZIP(), []int{4}
}

func (x *GetModelProviderResponse) GetModelProvider() *ModelProvider {
	if x != nil {
		return x.ModelProvider
	}
	return nil
}

type ListModelProvidersRequest struct {
	state         protoimpl.MessageState            `protogen:"open.v1"`
	Filter        *ListModelProvidersRequest_Filter `protobuf:"bytes,1,opt,name=filter,proto3" json:"filter,omitempty"`
	PageToken     string                            `protobuf:"bytes,2,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListModelProvidersRequest) Reset() {
	*x = ListModelProvidersRequest{}
	mi := &file_construct_v1_modelprovider_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListModelProvidersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListModelProvidersRequest) ProtoMessage() {}

func (x *ListModelProvidersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_construct_v1_modelprovider_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListModelProvidersRequest.ProtoReflect.Descriptor instead.
func (*ListModelProvidersRequest) Descriptor() ([]byte, []int) {
	return file_construct_v1_modelprovider_proto_rawDescGZIP(), []int{5}
}

func (x *ListModelProvidersRequest) GetFilter() *ListModelProvidersRequest_Filter {
	if x != nil {
		return x.Filter
	}
	return nil
}

func (x *ListModelProvidersRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

type ListModelProvidersResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ModelProviders []*ModelProvider       `protobuf:"bytes,1,rep,name=model_providers,json=modelProviders,proto3" json:"model_providers,omitempty"`
	NextPageToken  string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ListModelProvidersResponse) Reset() {
	*x = ListModelProvidersResponse{}
	mi := &file_construct_v1_modelprovider_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListModelProvidersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListModelProvidersResponse) ProtoMessage() {}

func (x *ListModelProvidersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_construct_v1_modelprovider_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListModelProvidersResponse.ProtoReflect.Descriptor instead.
func (*ListModelProvidersResponse) Descriptor() ([]byte, []int) {
	return file_construct_v1_modelprovider_proto_rawDescGZIP(), []int{6}
}

func (x *ListModelProvidersResponse) GetModelProviders() []*ModelProvider {
	if x != nil {
		return x.ModelProviders
	}
	return nil
}

func (x *ListModelProvidersResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

type UpdateModelProviderRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name  *string                `protobuf:"bytes,2,opt,name=name,proto3,oneof" json:"name,omitempty"`
	// Types that are valid to be assigned to Authentication:
	//
	//	*UpdateModelProviderRequest_ApiKey
	Authentication isUpdateModelProviderRequest_Authentication `protobuf_oneof:"authentication"`
	Enabled        *bool                                       `protobuf:"varint,30,opt,name=enabled,proto3,oneof" json:"enabled,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UpdateModelProviderRequest) Reset() {
	*x = UpdateModelProviderRequest{}
	mi := &file_construct_v1_modelprovider_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateModelProviderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateModelProviderRequest) ProtoMessage() {}

func (x *UpdateModelProviderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_construct_v1_modelprovider_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateModelProviderRequest.ProtoReflect.Descriptor instead.
func (*UpdateModelProviderRequest) Descriptor() ([]byte, []int) {
	return file_construct_v1_modelprovider_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateModelProviderRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateModelProviderRequest) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *UpdateModelProviderRequest) GetAuthentication() isUpdateModelProviderRequest_Authentication {
	if x != nil {
		return x.Authentication
	}
	return nil
}

func (x *UpdateModelProviderRequest) GetApiKey() string {
	if x != nil {
		if x, ok := x.Authentication.(*UpdateModelProviderRequest_ApiKey); ok {
			return x.ApiKey
		}
	}
	return ""
}

func (x *UpdateModelProviderRequest) GetEnabled() bool {
	if x != nil && x.Enabled != nil {
		return *x.Enabled
	}
	return false
}

type isUpdateModelProviderRequest_Authentication interface {
	isUpdateModelProviderRequest_Authentication()
}

type UpdateModelProviderRequest_ApiKey struct {
	ApiKey string `protobuf:"bytes,3,opt,name=api_key,json=apiKey,proto3,oneof"`
}

func (*UpdateModelProviderRequest_ApiKey) isUpdateModelProviderRequest_Authentication() {}

type UpdateModelProviderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ModelProvider *ModelProvider         `protobuf:"bytes,1,opt,name=model_provider,json=modelProvider,proto3" json:"model_provider,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateModelProviderResponse) Reset() {
	*x = UpdateModelProviderResponse{}
	mi := &file_construct_v1_modelprovider_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateModelProviderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateModelProviderResponse) ProtoMessage() {}

func (x *UpdateModelProviderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_construct_v1_modelprovider_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateModelProviderResponse.ProtoReflect.Descriptor instead.
func (*UpdateModelProviderResponse) Descriptor() ([]byte, []int) {
	return file_construct_v1_modelprovider_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateModelProviderResponse) GetModelProvider() *ModelProvider {
	if x != nil {
		return x.ModelProvider
	}
	return nil
}

type DeleteModelProviderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteModelProviderRequest) Reset() {
	*x = DeleteModelProviderRequest{}
	mi := &file_construct_v1_modelprovider_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteModelProviderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteModelProviderRequest) ProtoMessage() {}

func (x *DeleteModelProviderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_construct_v1_modelprovider_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteModelProviderRequest.ProtoReflect.Descriptor instead.
func (*DeleteModelProviderRequest) Descriptor() ([]byte, []int) {
	return file_construct_v1_modelprovider_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteModelProviderRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteModelProviderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteModelProviderResponse) Reset() {
	*x = DeleteModelProviderResponse{}
	mi := &file_construct_v1_modelprovider_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteModelProviderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteModelProviderResponse) ProtoMessage() {}

func (x *DeleteModelProviderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_construct_v1_modelprovider_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteModelProviderResponse.ProtoReflect.Descriptor instead.
func (*DeleteModelProviderResponse) Descriptor() ([]byte, []int) {
	return file_construct_v1_modelprovider_proto_rawDescGZIP(), []int{10}
}

type ListModelProvidersRequest_Filter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Enabled       *bool                  `protobuf:"varint,1,opt,name=enabled,proto3,oneof" json:"enabled,omitempty"`
	ProviderTypes []ModelProviderType    `protobuf:"varint,2,rep,packed,name=provider_types,json=providerTypes,proto3,enum=construct.v1.ModelProviderType" json:"provider_types,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListModelProvidersRequest_Filter) Reset() {
	*x = ListModelProvidersRequest_Filter{}
	mi := &file_construct_v1_modelprovider_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListModelProvidersRequest_Filter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListModelProvidersRequest_Filter) ProtoMessage() {}

func (x *ListModelProvidersRequest_Filter) ProtoReflect() protoreflect.Message {
	mi := &file_construct_v1_modelprovider_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListModelProvidersRequest_Filter.ProtoReflect.Descriptor instead.
func (*ListModelProvidersRequest_Filter) Descriptor() ([]byte, []int) {
	return file_construct_v1_modelprovider_proto_rawDescGZIP(), []int{5, 0}
}

func (x *ListModelProvidersRequest_Filter) GetEnabled() bool {
	if x != nil && x.Enabled != nil {
		return *x.Enabled
	}
	return false
}

func (x *ListModelProvidersRequest_Filter) GetProviderTypes() []ModelProviderType {
	if x != nil {
		return x.ProviderTypes
	}
	return nil
}

var File_construct_v1_modelprovider_proto protoreflect.FileDescriptor

const file_construct_v1_modelprovider_proto_rawDesc = "" +
	"\n" +
	" construct/v1/modelprovider.proto\x12\fconstruct.v1\x1a\x1bbuf/validate/validate.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xc5\x01\n" +
	"\x1aCreateModelProviderRequest\x12\x1e\n" +
	"\x04name\x18\x01 \x01(\tB\n" +
	"\xbaH\ar\x05\x10\x01\x18\xff\x01R\x04name\x12%\n" +
	"\aapi_key\x18\x02 \x01(\tB\n" +
	"\xbaH\ar\x05\x10\x01\x18\xff\x01H\x00R\x06apiKey\x12N\n" +
	"\rprovider_type\x18\x1e \x01(\x0e2\x1f.construct.v1.ModelProviderTypeB\b\xbaH\x05\x82\x01\x02\x10\x01R\fproviderTypeB\x10\n" +
	"\x0eauthentication\"i\n" +
	"\x1bCreateModelProviderResponse\x12J\n" +
	"\x0emodel_provider\x18\x01 \x01(\v2\x1b.construct.v1.ModelProviderB\x06\xbaH\x03\xc8\x01\x01R\rmodelProvider\"\xc1\x02\n" +
	"\rModelProvider\x12\x18\n" +
	"\x02id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\x02id\x12\x1e\n" +
	"\x04name\x18\x02 \x01(\tB\n" +
	"\xbaH\ar\x05\x10\x01\x18\xff\x01R\x04name\x12N\n" +
	"\rprovider_type\x18\x03 \x01(\x0e2\x1f.construct.v1.ModelProviderTypeB\b\xbaH\x05\x82\x01\x02\x10\x01R\fproviderType\x12 \n" +
	"\aenabled\x18\x04 \x01(\bB\x06\xbaH\x03\xc8\x01\x01R\aenabled\x12A\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampB\x06\xbaH\x03\xc8\x01\x01R\tcreatedAt\x12A\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampB\x06\xbaH\x03\xc8\x01\x01R\tupdatedAt\"3\n" +
	"\x17GetModelProviderRequest\x12\x18\n" +
	"\x02id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\x02id\"f\n" +
	"\x18GetModelProviderResponse\x12J\n" +
	"\x0emodel_provider\x18\x01 \x01(\v2\x1b.construct.v1.ModelProviderB\x06\xbaH\x03\xc8\x01\x01R\rmodelProvider\"\x94\x02\n" +
	"\x19ListModelProvidersRequest\x12F\n" +
	"\x06filter\x18\x01 \x01(\v2..construct.v1.ListModelProvidersRequest.FilterR\x06filter\x12'\n" +
	"\n" +
	"page_token\x18\x02 \x01(\tB\b\xbaH\x05r\x03\x18\xff\x01R\tpageToken\x1a\x85\x01\n" +
	"\x06Filter\x12\x1d\n" +
	"\aenabled\x18\x01 \x01(\bH\x00R\aenabled\x88\x01\x01\x12P\n" +
	"\x0eprovider_types\x18\x02 \x03(\x0e2\x1f.construct.v1.ModelProviderTypeB\b\xbaH\x05\x92\x01\x02\x10\n" +
	"R\rproviderTypesB\n" +
	"\n" +
	"\b_enabled\"\x8a\x01\n" +
	"\x1aListModelProvidersResponse\x12D\n" +
	"\x0fmodel_providers\x18\x01 \x03(\v2\x1b.construct.v1.ModelProviderR\x0emodelProviders\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"\xc8\x01\n" +
	"\x1aUpdateModelProviderRequest\x12\x18\n" +
	"\x02id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\x02id\x12#\n" +
	"\x04name\x18\x02 \x01(\tB\n" +
	"\xbaH\ar\x05\x10\x01\x18\xff\x01H\x01R\x04name\x88\x01\x01\x12%\n" +
	"\aapi_key\x18\x03 \x01(\tB\n" +
	"\xbaH\ar\x05\x10\x01\x18\xff\x01H\x00R\x06apiKey\x12\x1d\n" +
	"\aenabled\x18\x1e \x01(\bH\x02R\aenabled\x88\x01\x01B\x10\n" +
	"\x0eauthenticationB\a\n" +
	"\x05_nameB\n" +
	"\n" +
	"\b_enabled\"i\n" +
	"\x1bUpdateModelProviderResponse\x12J\n" +
	"\x0emodel_provider\x18\x01 \x01(\v2\x1b.construct.v1.ModelProviderB\x06\xbaH\x03\xc8\x01\x01R\rmodelProvider\"6\n" +
	"\x1aDeleteModelProviderRequest\x12\x18\n" +
	"\x02id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\x02id\"\x1d\n" +
	"\x1bDeleteModelProviderResponse*{\n" +
	"\x11ModelProviderType\x12#\n" +
	"\x1fMODEL_PROVIDER_TYPE_UNSPECIFIED\x10\x00\x12!\n" +
	"\x1dMODEL_PROVIDER_TYPE_ANTHROPIC\x10\x01\x12\x1e\n" +
	"\x1aMODEL_PROVIDER_TYPE_OPENAI\x10\x022\xb6\x04\n" +
	"\x14ModelProviderService\x12l\n" +
	"\x13CreateModelProvider\x12(.construct.v1.CreateModelProviderRequest\x1a).construct.v1.CreateModelProviderResponse\"\x00\x12f\n" +
	"\x10GetModelProvider\x12%.construct.v1.GetModelProviderRequest\x1a&.construct.v1.GetModelProviderResponse\"\x03\x90\x02\x01\x12l\n" +
	"\x12ListModelProviders\x12'.construct.v1.ListModelProvidersRequest\x1a(.construct.v1.ListModelProvidersResponse\"\x03\x90\x02\x01\x12l\n" +
	"\x13UpdateModelProvider\x12(.construct.v1.UpdateModelProviderRequest\x1a).construct.v1.UpdateModelProviderResponse\"\x00\x12l\n" +
	"\x13DeleteModelProvider\x12(.construct.v1.DeleteModelProviderRequest\x1a).construct.v1.DeleteModelProviderResponse\"\x00B(Z&github.com/furisto/construct/api/go/v1b\x06proto3"

var (
	file_construct_v1_modelprovider_proto_rawDescOnce sync.Once
	file_construct_v1_modelprovider_proto_rawDescData []byte
)

func file_construct_v1_modelprovider_proto_rawDescGZIP() []byte {
	file_construct_v1_modelprovider_proto_rawDescOnce.Do(func() {
		file_construct_v1_modelprovider_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_construct_v1_modelprovider_proto_rawDesc), len(file_construct_v1_modelprovider_proto_rawDesc)))
	})
	return file_construct_v1_modelprovider_proto_rawDescData
}

var file_construct_v1_modelprovider_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_construct_v1_modelprovider_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_construct_v1_modelprovider_proto_goTypes = []any{
	(ModelProviderType)(0),                   // 0: construct.v1.ModelProviderType
	(*CreateModelProviderRequest)(nil),       // 1: construct.v1.CreateModelProviderRequest
	(*CreateModelProviderResponse)(nil),      // 2: construct.v1.CreateModelProviderResponse
	(*ModelProvider)(nil),                    // 3: construct.v1.ModelProvider
	(*GetModelProviderRequest)(nil),          // 4: construct.v1.GetModelProviderRequest
	(*GetModelProviderResponse)(nil),         // 5: construct.v1.GetModelProviderResponse
	(*ListModelProvidersRequest)(nil),        // 6: construct.v1.ListModelProvidersRequest
	(*ListModelProvidersResponse)(nil),       // 7: construct.v1.ListModelProvidersResponse
	(*UpdateModelProviderRequest)(nil),       // 8: construct.v1.UpdateModelProviderRequest
	(*UpdateModelProviderResponse)(nil),      // 9: construct.v1.UpdateModelProviderResponse
	(*DeleteModelProviderRequest)(nil),       // 10: construct.v1.DeleteModelProviderRequest
	(*DeleteModelProviderResponse)(nil),      // 11: construct.v1.DeleteModelProviderResponse
	(*ListModelProvidersRequest_Filter)(nil), // 12: construct.v1.ListModelProvidersRequest.Filter
	(*timestamppb.Timestamp)(nil),            // 13: google.protobuf.Timestamp
}
var file_construct_v1_modelprovider_proto_depIdxs = []int32{
	0,  // 0: construct.v1.CreateModelProviderRequest.provider_type:type_name -> construct.v1.ModelProviderType
	3,  // 1: construct.v1.CreateModelProviderResponse.model_provider:type_name -> construct.v1.ModelProvider
	0,  // 2: construct.v1.ModelProvider.provider_type:type_name -> construct.v1.ModelProviderType
	13, // 3: construct.v1.ModelProvider.created_at:type_name -> google.protobuf.Timestamp
	13, // 4: construct.v1.ModelProvider.updated_at:type_name -> google.protobuf.Timestamp
	3,  // 5: construct.v1.GetModelProviderResponse.model_provider:type_name -> construct.v1.ModelProvider
	12, // 6: construct.v1.ListModelProvidersRequest.filter:type_name -> construct.v1.ListModelProvidersRequest.Filter
	3,  // 7: construct.v1.ListModelProvidersResponse.model_providers:type_name -> construct.v1.ModelProvider
	3,  // 8: construct.v1.UpdateModelProviderResponse.model_provider:type_name -> construct.v1.ModelProvider
	0,  // 9: construct.v1.ListModelProvidersRequest.Filter.provider_types:type_name -> construct.v1.ModelProviderType
	1,  // 10: construct.v1.ModelProviderService.CreateModelProvider:input_type -> construct.v1.CreateModelProviderRequest
	4,  // 11: construct.v1.ModelProviderService.GetModelProvider:input_type -> construct.v1.GetModelProviderRequest
	6,  // 12: construct.v1.ModelProviderService.ListModelProviders:input_type -> construct.v1.ListModelProvidersRequest
	8,  // 13: construct.v1.ModelProviderService.UpdateModelProvider:input_type -> construct.v1.UpdateModelProviderRequest
	10, // 14: construct.v1.ModelProviderService.DeleteModelProvider:input_type -> construct.v1.DeleteModelProviderRequest
	2,  // 15: construct.v1.ModelProviderService.CreateModelProvider:output_type -> construct.v1.CreateModelProviderResponse
	5,  // 16: construct.v1.ModelProviderService.GetModelProvider:output_type -> construct.v1.GetModelProviderResponse
	7,  // 17: construct.v1.ModelProviderService.ListModelProviders:output_type -> construct.v1.ListModelProvidersResponse
	9,  // 18: construct.v1.ModelProviderService.UpdateModelProvider:output_type -> construct.v1.UpdateModelProviderResponse
	11, // 19: construct.v1.ModelProviderService.DeleteModelProvider:output_type -> construct.v1.DeleteModelProviderResponse
	15, // [15:20] is the sub-list for method output_type
	10, // [10:15] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_construct_v1_modelprovider_proto_init() }
func file_construct_v1_modelprovider_proto_init() {
	if File_construct_v1_modelprovider_proto != nil {
		return
	}
	file_construct_v1_modelprovider_proto_msgTypes[0].OneofWrappers = []any{
		(*CreateModelProviderRequest_ApiKey)(nil),
	}
	file_construct_v1_modelprovider_proto_msgTypes[7].OneofWrappers = []any{
		(*UpdateModelProviderRequest_ApiKey)(nil),
	}
	file_construct_v1_modelprovider_proto_msgTypes[11].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_construct_v1_modelprovider_proto_rawDesc), len(file_construct_v1_modelprovider_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_construct_v1_modelprovider_proto_goTypes,
		DependencyIndexes: file_construct_v1_modelprovider_proto_depIdxs,
		EnumInfos:         file_construct_v1_modelprovider_proto_enumTypes,
		MessageInfos:      file_construct_v1_modelprovider_proto_msgTypes,
	}.Build()
	File_construct_v1_modelprovider_proto = out.File
	file_construct_v1_modelprovider_proto_goTypes = nil
	file_construct_v1_modelprovider_proto_depIdxs = nil
}
