// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: construct/v1/message.proto

package v1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/furisto/construct/api/go/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// MessageServiceName is the fully-qualified name of the MessageService service.
	MessageServiceName = "construct.v1.MessageService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// MessageServiceCreateMessageProcedure is the fully-qualified name of the MessageService's
	// CreateMessage RPC.
	MessageServiceCreateMessageProcedure = "/construct.v1.MessageService/CreateMessage"
	// MessageServiceGetMessageProcedure is the fully-qualified name of the MessageService's GetMessage
	// RPC.
	MessageServiceGetMessageProcedure = "/construct.v1.MessageService/GetMessage"
	// MessageServiceListMessagesProcedure is the fully-qualified name of the MessageService's
	// ListMessages RPC.
	MessageServiceListMessagesProcedure = "/construct.v1.MessageService/ListMessages"
	// MessageServiceUpdateMessageProcedure is the fully-qualified name of the MessageService's
	// UpdateMessage RPC.
	MessageServiceUpdateMessageProcedure = "/construct.v1.MessageService/UpdateMessage"
	// MessageServiceDeleteMessageProcedure is the fully-qualified name of the MessageService's
	// DeleteMessage RPC.
	MessageServiceDeleteMessageProcedure = "/construct.v1.MessageService/DeleteMessage"
	// MessageServiceSubscribeProcedure is the fully-qualified name of the MessageService's Subscribe
	// RPC.
	MessageServiceSubscribeProcedure = "/construct.v1.MessageService/Subscribe"
)

// MessageServiceClient is a client for the construct.v1.MessageService service.
type MessageServiceClient interface {
	CreateMessage(context.Context, *connect.Request[v1.CreateMessageRequest]) (*connect.Response[v1.CreateMessageResponse], error)
	GetMessage(context.Context, *connect.Request[v1.GetMessageRequest]) (*connect.Response[v1.GetMessageResponse], error)
	ListMessages(context.Context, *connect.Request[v1.ListMessagesRequest]) (*connect.Response[v1.ListMessagesResponse], error)
	UpdateMessage(context.Context, *connect.Request[v1.UpdateMessageRequest]) (*connect.Response[v1.UpdateMessageResponse], error)
	DeleteMessage(context.Context, *connect.Request[v1.DeleteMessageRequest]) (*connect.Response[v1.DeleteMessageResponse], error)
	Subscribe(context.Context, *connect.Request[v1.SubscribeRequest]) (*connect.ServerStreamForClient[v1.SubscribeResponse], error)
}

// NewMessageServiceClient constructs a client for the construct.v1.MessageService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewMessageServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) MessageServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	messageServiceMethods := v1.File_construct_v1_message_proto.Services().ByName("MessageService").Methods()
	return &messageServiceClient{
		createMessage: connect.NewClient[v1.CreateMessageRequest, v1.CreateMessageResponse](
			httpClient,
			baseURL+MessageServiceCreateMessageProcedure,
			connect.WithSchema(messageServiceMethods.ByName("CreateMessage")),
			connect.WithClientOptions(opts...),
		),
		getMessage: connect.NewClient[v1.GetMessageRequest, v1.GetMessageResponse](
			httpClient,
			baseURL+MessageServiceGetMessageProcedure,
			connect.WithSchema(messageServiceMethods.ByName("GetMessage")),
			connect.WithIdempotency(connect.IdempotencyNoSideEffects),
			connect.WithClientOptions(opts...),
		),
		listMessages: connect.NewClient[v1.ListMessagesRequest, v1.ListMessagesResponse](
			httpClient,
			baseURL+MessageServiceListMessagesProcedure,
			connect.WithSchema(messageServiceMethods.ByName("ListMessages")),
			connect.WithIdempotency(connect.IdempotencyNoSideEffects),
			connect.WithClientOptions(opts...),
		),
		updateMessage: connect.NewClient[v1.UpdateMessageRequest, v1.UpdateMessageResponse](
			httpClient,
			baseURL+MessageServiceUpdateMessageProcedure,
			connect.WithSchema(messageServiceMethods.ByName("UpdateMessage")),
			connect.WithClientOptions(opts...),
		),
		deleteMessage: connect.NewClient[v1.DeleteMessageRequest, v1.DeleteMessageResponse](
			httpClient,
			baseURL+MessageServiceDeleteMessageProcedure,
			connect.WithSchema(messageServiceMethods.ByName("DeleteMessage")),
			connect.WithClientOptions(opts...),
		),
		subscribe: connect.NewClient[v1.SubscribeRequest, v1.SubscribeResponse](
			httpClient,
			baseURL+MessageServiceSubscribeProcedure,
			connect.WithSchema(messageServiceMethods.ByName("Subscribe")),
			connect.WithClientOptions(opts...),
		),
	}
}

// messageServiceClient implements MessageServiceClient.
type messageServiceClient struct {
	createMessage *connect.Client[v1.CreateMessageRequest, v1.CreateMessageResponse]
	getMessage    *connect.Client[v1.GetMessageRequest, v1.GetMessageResponse]
	listMessages  *connect.Client[v1.ListMessagesRequest, v1.ListMessagesResponse]
	updateMessage *connect.Client[v1.UpdateMessageRequest, v1.UpdateMessageResponse]
	deleteMessage *connect.Client[v1.DeleteMessageRequest, v1.DeleteMessageResponse]
	subscribe     *connect.Client[v1.SubscribeRequest, v1.SubscribeResponse]
}

// CreateMessage calls construct.v1.MessageService.CreateMessage.
func (c *messageServiceClient) CreateMessage(ctx context.Context, req *connect.Request[v1.CreateMessageRequest]) (*connect.Response[v1.CreateMessageResponse], error) {
	return c.createMessage.CallUnary(ctx, req)
}

// GetMessage calls construct.v1.MessageService.GetMessage.
func (c *messageServiceClient) GetMessage(ctx context.Context, req *connect.Request[v1.GetMessageRequest]) (*connect.Response[v1.GetMessageResponse], error) {
	return c.getMessage.CallUnary(ctx, req)
}

// ListMessages calls construct.v1.MessageService.ListMessages.
func (c *messageServiceClient) ListMessages(ctx context.Context, req *connect.Request[v1.ListMessagesRequest]) (*connect.Response[v1.ListMessagesResponse], error) {
	return c.listMessages.CallUnary(ctx, req)
}

// UpdateMessage calls construct.v1.MessageService.UpdateMessage.
func (c *messageServiceClient) UpdateMessage(ctx context.Context, req *connect.Request[v1.UpdateMessageRequest]) (*connect.Response[v1.UpdateMessageResponse], error) {
	return c.updateMessage.CallUnary(ctx, req)
}

// DeleteMessage calls construct.v1.MessageService.DeleteMessage.
func (c *messageServiceClient) DeleteMessage(ctx context.Context, req *connect.Request[v1.DeleteMessageRequest]) (*connect.Response[v1.DeleteMessageResponse], error) {
	return c.deleteMessage.CallUnary(ctx, req)
}

// Subscribe calls construct.v1.MessageService.Subscribe.
func (c *messageServiceClient) Subscribe(ctx context.Context, req *connect.Request[v1.SubscribeRequest]) (*connect.ServerStreamForClient[v1.SubscribeResponse], error) {
	return c.subscribe.CallServerStream(ctx, req)
}

// MessageServiceHandler is an implementation of the construct.v1.MessageService service.
type MessageServiceHandler interface {
	CreateMessage(context.Context, *connect.Request[v1.CreateMessageRequest]) (*connect.Response[v1.CreateMessageResponse], error)
	GetMessage(context.Context, *connect.Request[v1.GetMessageRequest]) (*connect.Response[v1.GetMessageResponse], error)
	ListMessages(context.Context, *connect.Request[v1.ListMessagesRequest]) (*connect.Response[v1.ListMessagesResponse], error)
	UpdateMessage(context.Context, *connect.Request[v1.UpdateMessageRequest]) (*connect.Response[v1.UpdateMessageResponse], error)
	DeleteMessage(context.Context, *connect.Request[v1.DeleteMessageRequest]) (*connect.Response[v1.DeleteMessageResponse], error)
	Subscribe(context.Context, *connect.Request[v1.SubscribeRequest], *connect.ServerStream[v1.SubscribeResponse]) error
}

// NewMessageServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewMessageServiceHandler(svc MessageServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	messageServiceMethods := v1.File_construct_v1_message_proto.Services().ByName("MessageService").Methods()
	messageServiceCreateMessageHandler := connect.NewUnaryHandler(
		MessageServiceCreateMessageProcedure,
		svc.CreateMessage,
		connect.WithSchema(messageServiceMethods.ByName("CreateMessage")),
		connect.WithHandlerOptions(opts...),
	)
	messageServiceGetMessageHandler := connect.NewUnaryHandler(
		MessageServiceGetMessageProcedure,
		svc.GetMessage,
		connect.WithSchema(messageServiceMethods.ByName("GetMessage")),
		connect.WithIdempotency(connect.IdempotencyNoSideEffects),
		connect.WithHandlerOptions(opts...),
	)
	messageServiceListMessagesHandler := connect.NewUnaryHandler(
		MessageServiceListMessagesProcedure,
		svc.ListMessages,
		connect.WithSchema(messageServiceMethods.ByName("ListMessages")),
		connect.WithIdempotency(connect.IdempotencyNoSideEffects),
		connect.WithHandlerOptions(opts...),
	)
	messageServiceUpdateMessageHandler := connect.NewUnaryHandler(
		MessageServiceUpdateMessageProcedure,
		svc.UpdateMessage,
		connect.WithSchema(messageServiceMethods.ByName("UpdateMessage")),
		connect.WithHandlerOptions(opts...),
	)
	messageServiceDeleteMessageHandler := connect.NewUnaryHandler(
		MessageServiceDeleteMessageProcedure,
		svc.DeleteMessage,
		connect.WithSchema(messageServiceMethods.ByName("DeleteMessage")),
		connect.WithHandlerOptions(opts...),
	)
	messageServiceSubscribeHandler := connect.NewServerStreamHandler(
		MessageServiceSubscribeProcedure,
		svc.Subscribe,
		connect.WithSchema(messageServiceMethods.ByName("Subscribe")),
		connect.WithHandlerOptions(opts...),
	)
	return "/construct.v1.MessageService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case MessageServiceCreateMessageProcedure:
			messageServiceCreateMessageHandler.ServeHTTP(w, r)
		case MessageServiceGetMessageProcedure:
			messageServiceGetMessageHandler.ServeHTTP(w, r)
		case MessageServiceListMessagesProcedure:
			messageServiceListMessagesHandler.ServeHTTP(w, r)
		case MessageServiceUpdateMessageProcedure:
			messageServiceUpdateMessageHandler.ServeHTTP(w, r)
		case MessageServiceDeleteMessageProcedure:
			messageServiceDeleteMessageHandler.ServeHTTP(w, r)
		case MessageServiceSubscribeProcedure:
			messageServiceSubscribeHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedMessageServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedMessageServiceHandler struct{}

func (UnimplementedMessageServiceHandler) CreateMessage(context.Context, *connect.Request[v1.CreateMessageRequest]) (*connect.Response[v1.CreateMessageResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("construct.v1.MessageService.CreateMessage is not implemented"))
}

func (UnimplementedMessageServiceHandler) GetMessage(context.Context, *connect.Request[v1.GetMessageRequest]) (*connect.Response[v1.GetMessageResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("construct.v1.MessageService.GetMessage is not implemented"))
}

func (UnimplementedMessageServiceHandler) ListMessages(context.Context, *connect.Request[v1.ListMessagesRequest]) (*connect.Response[v1.ListMessagesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("construct.v1.MessageService.ListMessages is not implemented"))
}

func (UnimplementedMessageServiceHandler) UpdateMessage(context.Context, *connect.Request[v1.UpdateMessageRequest]) (*connect.Response[v1.UpdateMessageResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("construct.v1.MessageService.UpdateMessage is not implemented"))
}

func (UnimplementedMessageServiceHandler) DeleteMessage(context.Context, *connect.Request[v1.DeleteMessageRequest]) (*connect.Response[v1.DeleteMessageResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("construct.v1.MessageService.DeleteMessage is not implemented"))
}

func (UnimplementedMessageServiceHandler) Subscribe(context.Context, *connect.Request[v1.SubscribeRequest], *connect.ServerStream[v1.SubscribeResponse]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("construct.v1.MessageService.Subscribe is not implemented"))
}
