// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: construct/v1/modelprovider.proto

package v1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/furisto/construct/api/go/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// ModelProviderServiceName is the fully-qualified name of the ModelProviderService service.
	ModelProviderServiceName = "construct.v1.ModelProviderService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// ModelProviderServiceCreateModelProviderProcedure is the fully-qualified name of the
	// ModelProviderService's CreateModelProvider RPC.
	ModelProviderServiceCreateModelProviderProcedure = "/construct.v1.ModelProviderService/CreateModelProvider"
	// ModelProviderServiceGetModelProviderProcedure is the fully-qualified name of the
	// ModelProviderService's GetModelProvider RPC.
	ModelProviderServiceGetModelProviderProcedure = "/construct.v1.ModelProviderService/GetModelProvider"
	// ModelProviderServiceListModelProvidersProcedure is the fully-qualified name of the
	// ModelProviderService's ListModelProviders RPC.
	ModelProviderServiceListModelProvidersProcedure = "/construct.v1.ModelProviderService/ListModelProviders"
	// ModelProviderServiceUpdateModelProviderProcedure is the fully-qualified name of the
	// ModelProviderService's UpdateModelProvider RPC.
	ModelProviderServiceUpdateModelProviderProcedure = "/construct.v1.ModelProviderService/UpdateModelProvider"
	// ModelProviderServiceDeleteModelProviderProcedure is the fully-qualified name of the
	// ModelProviderService's DeleteModelProvider RPC.
	ModelProviderServiceDeleteModelProviderProcedure = "/construct.v1.ModelProviderService/DeleteModelProvider"
)

// ModelProviderServiceClient is a client for the construct.v1.ModelProviderService service.
type ModelProviderServiceClient interface {
	CreateModelProvider(context.Context, *connect.Request[v1.CreateModelProviderRequest]) (*connect.Response[v1.CreateModelProviderResponse], error)
	GetModelProvider(context.Context, *connect.Request[v1.GetModelProviderRequest]) (*connect.Response[v1.GetModelProviderResponse], error)
	ListModelProviders(context.Context, *connect.Request[v1.ListModelProvidersRequest]) (*connect.Response[v1.ListModelProvidersResponse], error)
	UpdateModelProvider(context.Context, *connect.Request[v1.UpdateModelProviderRequest]) (*connect.Response[v1.UpdateModelProviderResponse], error)
	DeleteModelProvider(context.Context, *connect.Request[v1.DeleteModelProviderRequest]) (*connect.Response[v1.DeleteModelProviderResponse], error)
}

// NewModelProviderServiceClient constructs a client for the construct.v1.ModelProviderService
// service. By default, it uses the Connect protocol with the binary Protobuf Codec, asks for
// gzipped responses, and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply
// the connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewModelProviderServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) ModelProviderServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	modelProviderServiceMethods := v1.File_construct_v1_modelprovider_proto.Services().ByName("ModelProviderService").Methods()
	return &modelProviderServiceClient{
		createModelProvider: connect.NewClient[v1.CreateModelProviderRequest, v1.CreateModelProviderResponse](
			httpClient,
			baseURL+ModelProviderServiceCreateModelProviderProcedure,
			connect.WithSchema(modelProviderServiceMethods.ByName("CreateModelProvider")),
			connect.WithClientOptions(opts...),
		),
		getModelProvider: connect.NewClient[v1.GetModelProviderRequest, v1.GetModelProviderResponse](
			httpClient,
			baseURL+ModelProviderServiceGetModelProviderProcedure,
			connect.WithSchema(modelProviderServiceMethods.ByName("GetModelProvider")),
			connect.WithIdempotency(connect.IdempotencyNoSideEffects),
			connect.WithClientOptions(opts...),
		),
		listModelProviders: connect.NewClient[v1.ListModelProvidersRequest, v1.ListModelProvidersResponse](
			httpClient,
			baseURL+ModelProviderServiceListModelProvidersProcedure,
			connect.WithSchema(modelProviderServiceMethods.ByName("ListModelProviders")),
			connect.WithIdempotency(connect.IdempotencyNoSideEffects),
			connect.WithClientOptions(opts...),
		),
		updateModelProvider: connect.NewClient[v1.UpdateModelProviderRequest, v1.UpdateModelProviderResponse](
			httpClient,
			baseURL+ModelProviderServiceUpdateModelProviderProcedure,
			connect.WithSchema(modelProviderServiceMethods.ByName("UpdateModelProvider")),
			connect.WithClientOptions(opts...),
		),
		deleteModelProvider: connect.NewClient[v1.DeleteModelProviderRequest, v1.DeleteModelProviderResponse](
			httpClient,
			baseURL+ModelProviderServiceDeleteModelProviderProcedure,
			connect.WithSchema(modelProviderServiceMethods.ByName("DeleteModelProvider")),
			connect.WithClientOptions(opts...),
		),
	}
}

// modelProviderServiceClient implements ModelProviderServiceClient.
type modelProviderServiceClient struct {
	createModelProvider *connect.Client[v1.CreateModelProviderRequest, v1.CreateModelProviderResponse]
	getModelProvider    *connect.Client[v1.GetModelProviderRequest, v1.GetModelProviderResponse]
	listModelProviders  *connect.Client[v1.ListModelProvidersRequest, v1.ListModelProvidersResponse]
	updateModelProvider *connect.Client[v1.UpdateModelProviderRequest, v1.UpdateModelProviderResponse]
	deleteModelProvider *connect.Client[v1.DeleteModelProviderRequest, v1.DeleteModelProviderResponse]
}

// CreateModelProvider calls construct.v1.ModelProviderService.CreateModelProvider.
func (c *modelProviderServiceClient) CreateModelProvider(ctx context.Context, req *connect.Request[v1.CreateModelProviderRequest]) (*connect.Response[v1.CreateModelProviderResponse], error) {
	return c.createModelProvider.CallUnary(ctx, req)
}

// GetModelProvider calls construct.v1.ModelProviderService.GetModelProvider.
func (c *modelProviderServiceClient) GetModelProvider(ctx context.Context, req *connect.Request[v1.GetModelProviderRequest]) (*connect.Response[v1.GetModelProviderResponse], error) {
	return c.getModelProvider.CallUnary(ctx, req)
}

// ListModelProviders calls construct.v1.ModelProviderService.ListModelProviders.
func (c *modelProviderServiceClient) ListModelProviders(ctx context.Context, req *connect.Request[v1.ListModelProvidersRequest]) (*connect.Response[v1.ListModelProvidersResponse], error) {
	return c.listModelProviders.CallUnary(ctx, req)
}

// UpdateModelProvider calls construct.v1.ModelProviderService.UpdateModelProvider.
func (c *modelProviderServiceClient) UpdateModelProvider(ctx context.Context, req *connect.Request[v1.UpdateModelProviderRequest]) (*connect.Response[v1.UpdateModelProviderResponse], error) {
	return c.updateModelProvider.CallUnary(ctx, req)
}

// DeleteModelProvider calls construct.v1.ModelProviderService.DeleteModelProvider.
func (c *modelProviderServiceClient) DeleteModelProvider(ctx context.Context, req *connect.Request[v1.DeleteModelProviderRequest]) (*connect.Response[v1.DeleteModelProviderResponse], error) {
	return c.deleteModelProvider.CallUnary(ctx, req)
}

// ModelProviderServiceHandler is an implementation of the construct.v1.ModelProviderService
// service.
type ModelProviderServiceHandler interface {
	CreateModelProvider(context.Context, *connect.Request[v1.CreateModelProviderRequest]) (*connect.Response[v1.CreateModelProviderResponse], error)
	GetModelProvider(context.Context, *connect.Request[v1.GetModelProviderRequest]) (*connect.Response[v1.GetModelProviderResponse], error)
	ListModelProviders(context.Context, *connect.Request[v1.ListModelProvidersRequest]) (*connect.Response[v1.ListModelProvidersResponse], error)
	UpdateModelProvider(context.Context, *connect.Request[v1.UpdateModelProviderRequest]) (*connect.Response[v1.UpdateModelProviderResponse], error)
	DeleteModelProvider(context.Context, *connect.Request[v1.DeleteModelProviderRequest]) (*connect.Response[v1.DeleteModelProviderResponse], error)
}

// NewModelProviderServiceHandler builds an HTTP handler from the service implementation. It returns
// the path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewModelProviderServiceHandler(svc ModelProviderServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	modelProviderServiceMethods := v1.File_construct_v1_modelprovider_proto.Services().ByName("ModelProviderService").Methods()
	modelProviderServiceCreateModelProviderHandler := connect.NewUnaryHandler(
		ModelProviderServiceCreateModelProviderProcedure,
		svc.CreateModelProvider,
		connect.WithSchema(modelProviderServiceMethods.ByName("CreateModelProvider")),
		connect.WithHandlerOptions(opts...),
	)
	modelProviderServiceGetModelProviderHandler := connect.NewUnaryHandler(
		ModelProviderServiceGetModelProviderProcedure,
		svc.GetModelProvider,
		connect.WithSchema(modelProviderServiceMethods.ByName("GetModelProvider")),
		connect.WithIdempotency(connect.IdempotencyNoSideEffects),
		connect.WithHandlerOptions(opts...),
	)
	modelProviderServiceListModelProvidersHandler := connect.NewUnaryHandler(
		ModelProviderServiceListModelProvidersProcedure,
		svc.ListModelProviders,
		connect.WithSchema(modelProviderServiceMethods.ByName("ListModelProviders")),
		connect.WithIdempotency(connect.IdempotencyNoSideEffects),
		connect.WithHandlerOptions(opts...),
	)
	modelProviderServiceUpdateModelProviderHandler := connect.NewUnaryHandler(
		ModelProviderServiceUpdateModelProviderProcedure,
		svc.UpdateModelProvider,
		connect.WithSchema(modelProviderServiceMethods.ByName("UpdateModelProvider")),
		connect.WithHandlerOptions(opts...),
	)
	modelProviderServiceDeleteModelProviderHandler := connect.NewUnaryHandler(
		ModelProviderServiceDeleteModelProviderProcedure,
		svc.DeleteModelProvider,
		connect.WithSchema(modelProviderServiceMethods.ByName("DeleteModelProvider")),
		connect.WithHandlerOptions(opts...),
	)
	return "/construct.v1.ModelProviderService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case ModelProviderServiceCreateModelProviderProcedure:
			modelProviderServiceCreateModelProviderHandler.ServeHTTP(w, r)
		case ModelProviderServiceGetModelProviderProcedure:
			modelProviderServiceGetModelProviderHandler.ServeHTTP(w, r)
		case ModelProviderServiceListModelProvidersProcedure:
			modelProviderServiceListModelProvidersHandler.ServeHTTP(w, r)
		case ModelProviderServiceUpdateModelProviderProcedure:
			modelProviderServiceUpdateModelProviderHandler.ServeHTTP(w, r)
		case ModelProviderServiceDeleteModelProviderProcedure:
			modelProviderServiceDeleteModelProviderHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedModelProviderServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedModelProviderServiceHandler struct{}

func (UnimplementedModelProviderServiceHandler) CreateModelProvider(context.Context, *connect.Request[v1.CreateModelProviderRequest]) (*connect.Response[v1.CreateModelProviderResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("construct.v1.ModelProviderService.CreateModelProvider is not implemented"))
}

func (UnimplementedModelProviderServiceHandler) GetModelProvider(context.Context, *connect.Request[v1.GetModelProviderRequest]) (*connect.Response[v1.GetModelProviderResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("construct.v1.ModelProviderService.GetModelProvider is not implemented"))
}

func (UnimplementedModelProviderServiceHandler) ListModelProviders(context.Context, *connect.Request[v1.ListModelProvidersRequest]) (*connect.Response[v1.ListModelProvidersResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("construct.v1.ModelProviderService.ListModelProviders is not implemented"))
}

func (UnimplementedModelProviderServiceHandler) UpdateModelProvider(context.Context, *connect.Request[v1.UpdateModelProviderRequest]) (*connect.Response[v1.UpdateModelProviderResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("construct.v1.ModelProviderService.UpdateModelProvider is not implemented"))
}

func (UnimplementedModelProviderServiceHandler) DeleteModelProvider(context.Context, *connect.Request[v1.DeleteModelProviderRequest]) (*connect.Response[v1.DeleteModelProviderResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("construct.v1.ModelProviderService.DeleteModelProvider is not implemented"))
}
