// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: construct/v1/model.proto

package v1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/furisto/construct/api/go/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// ModelServiceName is the fully-qualified name of the ModelService service.
	ModelServiceName = "construct.v1.ModelService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// ModelServiceCreateModelProcedure is the fully-qualified name of the ModelService's CreateModel
	// RPC.
	ModelServiceCreateModelProcedure = "/construct.v1.ModelService/CreateModel"
	// ModelServiceGetModelProcedure is the fully-qualified name of the ModelService's GetModel RPC.
	ModelServiceGetModelProcedure = "/construct.v1.ModelService/GetModel"
	// ModelServiceListModelsProcedure is the fully-qualified name of the ModelService's ListModels RPC.
	ModelServiceListModelsProcedure = "/construct.v1.ModelService/ListModels"
	// ModelServiceUpdateModelProcedure is the fully-qualified name of the ModelService's UpdateModel
	// RPC.
	ModelServiceUpdateModelProcedure = "/construct.v1.ModelService/UpdateModel"
	// ModelServiceDeleteModelProcedure is the fully-qualified name of the ModelService's DeleteModel
	// RPC.
	ModelServiceDeleteModelProcedure = "/construct.v1.ModelService/DeleteModel"
)

// ModelServiceClient is a client for the construct.v1.ModelService service.
type ModelServiceClient interface {
	CreateModel(context.Context, *connect.Request[v1.CreateModelRequest]) (*connect.Response[v1.CreateModelResponse], error)
	GetModel(context.Context, *connect.Request[v1.GetModelRequest]) (*connect.Response[v1.GetModelResponse], error)
	ListModels(context.Context, *connect.Request[v1.ListModelsRequest]) (*connect.Response[v1.ListModelsResponse], error)
	UpdateModel(context.Context, *connect.Request[v1.UpdateModelRequest]) (*connect.Response[v1.UpdateModelResponse], error)
	DeleteModel(context.Context, *connect.Request[v1.DeleteModelRequest]) (*connect.Response[v1.DeleteModelResponse], error)
}

// NewModelServiceClient constructs a client for the construct.v1.ModelService service. By default,
// it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and
// sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC()
// or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewModelServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) ModelServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	modelServiceMethods := v1.File_construct_v1_model_proto.Services().ByName("ModelService").Methods()
	return &modelServiceClient{
		createModel: connect.NewClient[v1.CreateModelRequest, v1.CreateModelResponse](
			httpClient,
			baseURL+ModelServiceCreateModelProcedure,
			connect.WithSchema(modelServiceMethods.ByName("CreateModel")),
			connect.WithClientOptions(opts...),
		),
		getModel: connect.NewClient[v1.GetModelRequest, v1.GetModelResponse](
			httpClient,
			baseURL+ModelServiceGetModelProcedure,
			connect.WithSchema(modelServiceMethods.ByName("GetModel")),
			connect.WithIdempotency(connect.IdempotencyNoSideEffects),
			connect.WithClientOptions(opts...),
		),
		listModels: connect.NewClient[v1.ListModelsRequest, v1.ListModelsResponse](
			httpClient,
			baseURL+ModelServiceListModelsProcedure,
			connect.WithSchema(modelServiceMethods.ByName("ListModels")),
			connect.WithIdempotency(connect.IdempotencyNoSideEffects),
			connect.WithClientOptions(opts...),
		),
		updateModel: connect.NewClient[v1.UpdateModelRequest, v1.UpdateModelResponse](
			httpClient,
			baseURL+ModelServiceUpdateModelProcedure,
			connect.WithSchema(modelServiceMethods.ByName("UpdateModel")),
			connect.WithClientOptions(opts...),
		),
		deleteModel: connect.NewClient[v1.DeleteModelRequest, v1.DeleteModelResponse](
			httpClient,
			baseURL+ModelServiceDeleteModelProcedure,
			connect.WithSchema(modelServiceMethods.ByName("DeleteModel")),
			connect.WithClientOptions(opts...),
		),
	}
}

// modelServiceClient implements ModelServiceClient.
type modelServiceClient struct {
	createModel *connect.Client[v1.CreateModelRequest, v1.CreateModelResponse]
	getModel    *connect.Client[v1.GetModelRequest, v1.GetModelResponse]
	listModels  *connect.Client[v1.ListModelsRequest, v1.ListModelsResponse]
	updateModel *connect.Client[v1.UpdateModelRequest, v1.UpdateModelResponse]
	deleteModel *connect.Client[v1.DeleteModelRequest, v1.DeleteModelResponse]
}

// CreateModel calls construct.v1.ModelService.CreateModel.
func (c *modelServiceClient) CreateModel(ctx context.Context, req *connect.Request[v1.CreateModelRequest]) (*connect.Response[v1.CreateModelResponse], error) {
	return c.createModel.CallUnary(ctx, req)
}

// GetModel calls construct.v1.ModelService.GetModel.
func (c *modelServiceClient) GetModel(ctx context.Context, req *connect.Request[v1.GetModelRequest]) (*connect.Response[v1.GetModelResponse], error) {
	return c.getModel.CallUnary(ctx, req)
}

// ListModels calls construct.v1.ModelService.ListModels.
func (c *modelServiceClient) ListModels(ctx context.Context, req *connect.Request[v1.ListModelsRequest]) (*connect.Response[v1.ListModelsResponse], error) {
	return c.listModels.CallUnary(ctx, req)
}

// UpdateModel calls construct.v1.ModelService.UpdateModel.
func (c *modelServiceClient) UpdateModel(ctx context.Context, req *connect.Request[v1.UpdateModelRequest]) (*connect.Response[v1.UpdateModelResponse], error) {
	return c.updateModel.CallUnary(ctx, req)
}

// DeleteModel calls construct.v1.ModelService.DeleteModel.
func (c *modelServiceClient) DeleteModel(ctx context.Context, req *connect.Request[v1.DeleteModelRequest]) (*connect.Response[v1.DeleteModelResponse], error) {
	return c.deleteModel.CallUnary(ctx, req)
}

// ModelServiceHandler is an implementation of the construct.v1.ModelService service.
type ModelServiceHandler interface {
	CreateModel(context.Context, *connect.Request[v1.CreateModelRequest]) (*connect.Response[v1.CreateModelResponse], error)
	GetModel(context.Context, *connect.Request[v1.GetModelRequest]) (*connect.Response[v1.GetModelResponse], error)
	ListModels(context.Context, *connect.Request[v1.ListModelsRequest]) (*connect.Response[v1.ListModelsResponse], error)
	UpdateModel(context.Context, *connect.Request[v1.UpdateModelRequest]) (*connect.Response[v1.UpdateModelResponse], error)
	DeleteModel(context.Context, *connect.Request[v1.DeleteModelRequest]) (*connect.Response[v1.DeleteModelResponse], error)
}

// NewModelServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewModelServiceHandler(svc ModelServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	modelServiceMethods := v1.File_construct_v1_model_proto.Services().ByName("ModelService").Methods()
	modelServiceCreateModelHandler := connect.NewUnaryHandler(
		ModelServiceCreateModelProcedure,
		svc.CreateModel,
		connect.WithSchema(modelServiceMethods.ByName("CreateModel")),
		connect.WithHandlerOptions(opts...),
	)
	modelServiceGetModelHandler := connect.NewUnaryHandler(
		ModelServiceGetModelProcedure,
		svc.GetModel,
		connect.WithSchema(modelServiceMethods.ByName("GetModel")),
		connect.WithIdempotency(connect.IdempotencyNoSideEffects),
		connect.WithHandlerOptions(opts...),
	)
	modelServiceListModelsHandler := connect.NewUnaryHandler(
		ModelServiceListModelsProcedure,
		svc.ListModels,
		connect.WithSchema(modelServiceMethods.ByName("ListModels")),
		connect.WithIdempotency(connect.IdempotencyNoSideEffects),
		connect.WithHandlerOptions(opts...),
	)
	modelServiceUpdateModelHandler := connect.NewUnaryHandler(
		ModelServiceUpdateModelProcedure,
		svc.UpdateModel,
		connect.WithSchema(modelServiceMethods.ByName("UpdateModel")),
		connect.WithHandlerOptions(opts...),
	)
	modelServiceDeleteModelHandler := connect.NewUnaryHandler(
		ModelServiceDeleteModelProcedure,
		svc.DeleteModel,
		connect.WithSchema(modelServiceMethods.ByName("DeleteModel")),
		connect.WithHandlerOptions(opts...),
	)
	return "/construct.v1.ModelService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case ModelServiceCreateModelProcedure:
			modelServiceCreateModelHandler.ServeHTTP(w, r)
		case ModelServiceGetModelProcedure:
			modelServiceGetModelHandler.ServeHTTP(w, r)
		case ModelServiceListModelsProcedure:
			modelServiceListModelsHandler.ServeHTTP(w, r)
		case ModelServiceUpdateModelProcedure:
			modelServiceUpdateModelHandler.ServeHTTP(w, r)
		case ModelServiceDeleteModelProcedure:
			modelServiceDeleteModelHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedModelServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedModelServiceHandler struct{}

func (UnimplementedModelServiceHandler) CreateModel(context.Context, *connect.Request[v1.CreateModelRequest]) (*connect.Response[v1.CreateModelResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("construct.v1.ModelService.CreateModel is not implemented"))
}

func (UnimplementedModelServiceHandler) GetModel(context.Context, *connect.Request[v1.GetModelRequest]) (*connect.Response[v1.GetModelResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("construct.v1.ModelService.GetModel is not implemented"))
}

func (UnimplementedModelServiceHandler) ListModels(context.Context, *connect.Request[v1.ListModelsRequest]) (*connect.Response[v1.ListModelsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("construct.v1.ModelService.ListModels is not implemented"))
}

func (UnimplementedModelServiceHandler) UpdateModel(context.Context, *connect.Request[v1.UpdateModelRequest]) (*connect.Response[v1.UpdateModelResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("construct.v1.ModelService.UpdateModel is not implemented"))
}

func (UnimplementedModelServiceHandler) DeleteModel(context.Context, *connect.Request[v1.DeleteModelRequest]) (*connect.Response[v1.DeleteModelResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("construct.v1.ModelService.DeleteModel is not implemented"))
}
